"""Complete the held-out-instance split with individually written questions."""
from .held_question_authoring import d,p,field,associated,comparison,append_batch
r233,a233,b233=comparison(233)
q=[
f'What score sum belongs to posts written by holders of the {p(200,"badge")!r} badge, counting posts once?',
f'How much reputation is held in total by the distinct {d(201)}?',
f'Which of {d(202)} leads on stored usage count? Show the tag name and count.',
f'Count distinct questions in {d(203)} scoring no less than {p(203,"condition")}.',
f'Average stored usage counts over the different tags on posts commented on by {p(204,"name")!r}.',
f'What stored usage count is recorded on average for {d(205)}?',
f'Rank {d(206)} by score and show up to {p(206,"k")} of the best, with their {field(206)} and score.',
f'What is mean post score in {d(207)}?',
f'Average the scores for questions in {d(208)}.',
f'Count questions in {d(209)} whose scores additionally meet a minimum of {p(209,"condition")}.',
f'How high is the average score of comments by {p(210,"name")!r}?',
f'For tags on posts written by {p(211,"name")!r}, show tag names with counts of distinct qualifying {associated(211)}.',
f'Alphabetize a list of distinct {field(212)} for {d(212)}.',
f'How many separate questions has user {p(213,"anchor")} voted on?',
f'What is the smallest post score recorded within {d(214)}?',
f'What unique {field(215)} come from {d(215)}? Show an alphabetical list.',
f'How high is the maximum score of posts with revision activity by {p(216,"name")!r}?',
f'Total stored usage counts of the different tags on posts with revision activity by {p(217,"name")!r}.',
f'How many authored posts are recorded for user {p(218,"anchor")}?',
f'Add scores of the distinct {d(219)}.',
f'List unique tag names for {d(220)}, in alphabetical order.',
f'Combine the reputation of {d(221)}, using each distinct author once.',
f'For the distinct {d(222)}, find average reputation.',
f'What do scores of distinct questions answered by answers created on {p(223,"date")} total?',
f'Find the greatest reputation of users sharing badges with user {p(224,"anchor")}.',
f'What combined score results from {d(225)}?',
f'What score do posts voted on by {p(226,"name")!r} average, counting each post once?',
f'What score is achieved on average by the distinct {d(227)}?',
f'Which post commented on by user {p(228,"anchor")} scores lowest? Show its {field(228)} and score.',
f'Average the scores over the distinct {d(229)}.',
f'Find posts in {d(230)} with at least {p(230,"threshold")} distinct qualifying {associated(230)}. List their {field(230)} and counts.',
f'What is the mean score of posts authored by {p(231,"name")!r}?',
f'How many comments by {p(232,"name")!r} meet a score threshold of {p(232,"condition")} or more?',
f'What is the combined score for {r233} associated with {a233}, minus that for {b233}? Count posts once within each named user’s total.',
f'What mean score do the distinct {d(234)} have?',
f'Give each post by {p(235,"name")!r} with its {field(235)} and score.',
f'Show the highest-scoring accepted answer to questions titled {p(236,"title")!r}, using its first 120 body characters and score.',
f'How high is average reputation for {d(237)}?',
f'What reputation do the distinct {d(238)} average?',
f'Count separate comments in {d(239)}, avoiding repeated counts of a comment.',
f'Which comment by {p(240,"name")!r} scores best? Give its first 120 text characters and score.',
f'What do the scores of distinct posts voted on by {p(241,"name")!r} add up to?',
f'For posts commented on by users who joined on {p(242,"date")}, what percentage score above zero? Deduplicate posts and keep missing scores in the denominator.',
f'Calculate mean reputation across {d(243)}.',
f'What is the highest score earned by a post written by a holder of the {p(244,"badge")!r} badge?',
f'Combine the scores of comments by user {p(245,"anchor")}.',
f'How low is the minimum score of comments by {p(246,"name")!r}?',
f'What share of distinct {d(247)} score positively, expressed as a percentage? Include missing-score posts in the denominator.',
f'Average reputation for {d(248)}.',
f'What score does the lowest-scoring post voted on by {p(249,"name")!r} have?',
f'How many different tags satisfy {d(250)}?',
f'Show the name and count of the second most-used tag in {d(251)}, based on stored usage counts.',
f'For user {p(252,"anchor")}, identify their top-scoring post by its {field(252)} and show its score.',
f'What count of users in {d(253)} have reputation of at least {p(253,"condition")}?',
f'What is the minimum score for questions answered by answer {p(254,"anchor")}?',
f'Which wiki post for tag {p(255,"name")!r} has the smallest score? Give its {field(255)} and score.',
f'Find the least reputation held by {d(256)}.',
f'Give the {field(257)} and score for the post ranking lowest on score among posts voted on by {p(257,"name")!r}.',
f'What post with revision activity by {p(258,"name")!r} has the greatest score? Include its {field(258)} and score.',
f'Among comments by users who joined on {p(259,"date")}, what score is highest?',
f'What sum of scores comes from the distinct {d(260)}?',
f'Total reputation for {d(261)}, once per author.',
f'What is the reputation sum over {d(262)}?',
f'Only include scores of {p(263,"condition")} or above: what score total results from the distinct {d(263)}?'
]
from .held_question_edits import EDITS
q=[EDITS.get(index,sentence) for index,sentence in enumerate(q,200)]

if __name__=='__main__':append_batch(200,q)
