"""Complete the frozen sample with individually written novel combinations."""
from .held_question_authoring import d,p,field,associated,comparison,append_batch
r620,a620,b620=comparison(620)
q=[
f'What reputation do authors of posts linked to from posts with revision activity by user {p(564,"anchor")} have on average?',
f'How many different posts voted on by user {p(565,"anchor")} have comments?',
f'Give up to {p(566,"k")} highest-scoring posts commented on by holders of the {p(566,"badge")!r} badge, showing each {field(566)} and score.',
f'Which author has the smallest reputation among {d(567)}? Give their display name and reputation.',
f'List distinct authors of posts linked to from posts titled {p(568,"title")!r}, with display names and reputation.',
f'What is the least reputation held by an author of posts linked to from posts by user {p(569,"anchor")}?',
f'Add reputation of distinct authors without a recorded location among authors of accepted answers to questions answered by {p(570,"name")!r}.',
f'What average score do distinct posts created in {p(571,"year")} and authored by holders of the {p(571,"badge")!r} badge have?',
f'Which authors wrote at least {p(572,"threshold")} distinct questions answered by users who joined on {p(572,"date")}? Show display names and qualifying question counts.',
f'Show up to {p(573,"k")} most reputable {d(573)}, giving display names and reputation.',
f'How many different questions were authored by holders of the {p(574,"badge")!r} badge?',
f'What combined reputation do distinct authors of posts linked to from posts by {p(575,"name")!r} have?',
f'Who wrote posts linked to from posts commented on by {p(576,"name")!r}? List distinct authors’ display names and reputation.',
f'For authors of accepted answers to questions titled {p(577,"title")!r}, give display names and counts of distinct qualifying accepted answers.',
f'For {d(578)}, list up to {p(578,"k")} highest-reputation authors with display names and reputation.',
f'Count different authors of accepted answers to questions answered by users who joined on {p(579,"date")}.',
f'Total the reputation of the distinct authors of posts linked to from posts titled {p(580,"title")!r}.',
f'How many distinct tags on posts with revision activity by {p(581,"name")!r} contain {p(581,"text")!r} in their name, with case-sensitive matching?',
f'Find average reputation of authors with a recorded location among authors of posts linked to from posts commented on by {p(582,"name")!r}.',
f'How many different users share at least one badge with {p(583,"name")!r}?',
f'What reputation do {d(584)} average?',
f'Find the lowest score of any of {d(585)}.',
f'What reputation is highest among authors of posts linked to from posts titled {p(586,"title")!r}?',
f'What is the maximum author reputation among authors of posts linked to from posts by users who joined on {p(587,"date")}?',
f'Give up to {p(588,"k")} highest-scoring {d(588)}, with their {field(588)} and scores.',
f'What mean reputation is held by authors of accepted answers to question {p(589,"anchor")}?',
f'Calculate a reputation sum over distinct authors of questions answered by {p(590,"name")!r} who have no recorded location.',
f'Count the different posts satisfying {d(591)}, matching the title prefix case-sensitively.',
f'How high is the maximum reputation of an author of accepted answers to questions titled {p(592,"title")!r}?',
f'Show the {p(593,"k")} most reputable {d(593)}, with display names and reputation.',
f'Total reputation for the distinct authors of posts linked to from posts commented on by {p(594,"name")!r}.',
f'How many separate posts has {p(595,"name")!r} commented on?',
f'What mean score do distinct comments by authors of accepted answers to questions titled {p(596,"title")!r} have?',
f'Combine reputation of distinct authors of accepted answers to questions answered by {p(597,"name")!r}.',
f'Rank posts with revision activity by {p(598,"name")!r} on score. Show up to {p(598,"k")} best posts with each {field(598)} and score.',
f'What post commented on by a holder of the {p(599,"badge")!r} badge has the smallest score? Show its {field(599)} and score.',
f'List distinct {d(600)} as display names with reputation.',
f'Which post with revision activity by user {p(601,"anchor")} scores lowest? Give its {field(601)} and score.',
f'For {d(602)}, calculate their average reputation.',
f'Average scores of distinct comments by authors of posts linked to from posts by {p(603,"name")!r}.',
f'Show the display name and reputation of the least reputable author of accepted answers to questions titled {p(604,"title")!r}.',
f'What tags occur on posts with revision activity by user {p(605,"anchor")}? List distinct names and stored usage counts.',
f'What is average reputation for authors with a recorded location among authors of posts linked to from posts with revision activity by user {p(606,"anchor")}?',
f'Count the different tags on posts authored by {p(607,"name")!r}.',
f'What total score do distinct comments by authors of accepted answers to questions titled {p(608,"title")!r} have?',
f'For authors of accepted answers to questions answered by {p(609,"name")!r}, show display names and counts of distinct qualifying accepted answers.',
f'Give display names of authors of posts linked to from posts titled {p(610,"title")!r}, with the number of distinct qualifying linked posts each authored.',
f'What is average stored usage count among the different tags on posts with revision activity by users joining on {p(611,"date")}?',
f'Add reputation of the distinct authors of posts linked to from posts by holders of the {p(612,"badge")!r} badge.',
f'For users sharing a badge with {p(613,"name")!r}, sum reputation only for distinct users with no recorded location.',
f'Calculate mean reputation of {d(614)}, counting each author once.',
f'What total reputation is held by distinct authors of accepted answers to questions answered by users who joined on {p(615,"date")}?',
f'For posts commented on by users joining on {p(616,"date")}, list up to {p(616,"k")} highest-scoring posts with their {field(616)} and score.',
f'Which of {d(617)} have at least {p(617,"threshold")} distinct qualifying posts? Show display names and post counts.',
f'How many different authors wrote posts linked to from posts commented on by {p(618,"name")!r}?',
f'What combined reputation do authors of accepted answers to question {p(619,"anchor")} hold, counting an author once?',
f'For {r620}, calculate reputation totals associated with {a620} and {b620}, using distinct authors per named user. Give the first total minus the second.',
f'Show the top {p(621,"k")} {d(621)} by reputation, including display names and reputation.',
f'Which user sharing a badge with {p(622,"name")!r} has the greatest reputation? Give their display name and reputation.',
f'Give the {field(623)} and score of the highest-scoring post commented on by a holder of the {p(623,"badge")!r} badge.'
]
from .held_question_edits import EDITS
q=[EDITS.get(index,sentence) for index,sentence in enumerate(q,564)]

if __name__=='__main__':append_batch(564,q)
