"""Individual language corrections from reviewing saved held-out questions."""
from .held_question_authoring import d,p,field
EDITS={
5:f'List the different posts linked to from posts titled {p(5,"title")!r}, showing each {field(5)} and score.',
16:f'Within the inclusive score interval {p(16,"lower")} to {p(16,"upper")}, how many posts additionally score at least {p(16,"condition")}?',
23:f'Who has the greatest reputation among {d(23)}? Give the display name and reputation.',
26:f'Which of {d(26)} have at least {p(26,"threshold")} distinct comments by the qualifying authors? Show each {field(26)} and comment count.',
57:f'For posts linked to from posts titled {p(57,"title")!r}, add scores of at least {p(57,"condition")} once per distinct linked post.',
72:f'How many distinct questions answered by answers created on {p(72,"date")} reach a score of {p(72,"condition")} or more?',
99:f'List posts with at least {p(99,"threshold")} distinct comments by users who joined on {p(99,"date")}, giving each {field(99)} and the count of those comments.',
140:f'For comments by authors of accepted answers to questions titled {p(140,"title")!r}, show each comment’s first 120 text characters and count of distinct qualifying authors.',
146:f'Which linked post scores highest for posts titled {p(146,"title")!r}? Show its {field(146)} with the score.',
149:f'How many posts scoring between {p(149,"lower")} and {p(149,"upper")} inclusive additionally have a score of {p(149,"condition")} or more?',
156:f'Who is most reputable among {d(156)}? Give their display name and reputation.',
178:f'Find the lowest-scoring post linked to from posts titled {p(178,"title")!r}, including its {field(178)} and score.',
203:f'How many distinct questions answered by answers created on {p(203,"date")} score no less than {p(203,"condition")}?',
208:f'Average scores over questions scoring between {p(208,"lower")} and {p(208,"upper")} inclusive.',
209:f'For questions scoring between {p(209,"lower")} and {p(209,"upper")} inclusive, how many also meet a score minimum of {p(209,"condition")}?',
230:f'Find posts with at least {p(230,"threshold")} distinct comments written by users joining on {p(230,"date")}; give each {field(230)} and its count of those comments.',
239:f'How many distinct comments were written by authors of posts linked to from posts by user {p(239,"anchor")}?',
251:f'Among {d(251)}, show the name and stored usage count of the second most-used tag.',
253:f'For users with reputation between {p(253,"lower")} and {p(253,"upper")} inclusive, count those with reputation additionally reaching {p(253,"condition")} or above.',
305:f'Count distinct tags appearing on posts by authors of accepted answers to questions created on {p(305,"date")}.',
379:f'Find the largest stored usage count among tags on posts by authors of accepted answers to question {p(379,"anchor")}.',
395:f'What tag is most-used among {d(395)}, according to stored usage counts? Give its name and count.',
396:f'Count the distinct tags on posts by authors of accepted answers to questions titled {p(396,"title")!r} whose names begin with {p(396,"text")!r}, case-sensitively.',
422:f'For each of {d(422)}, show its name and number of distinct qualifying posts carrying that tag.',
425:f'List tags on at least {p(425,"threshold")} distinct posts by authors of accepted answers to questions titled {p(425,"title")!r}. Give tag names and those post counts.',
438:f'For posts titled {p(438,"title")!r}, take authors of linked posts and posts those authors commented on. How many different commented-on posts contain {p(438,"text")!r} in their titles, matching case?',
441:f'Which tag is least-used among {d(441)}, based on stored usage count? Give its name and count.',
463:f'What is the count of different tags meeting {d(463)}?',
474:f'Show up to {p(474,"k")} highest-scoring posts linked to from posts titled {p(474,"title")!r}, with their {field(474)} and score.',
481:f'For comments by authors of accepted answers to questions titled {p(481,"title")!r}, show the lowest-scoring comment’s first 120 text characters and score.',
493:f'List up to {p(493,"k")} highest-scoring comments by authors of accepted answers to questions titled {p(493,"title")!r}, showing their first 120 text characters and scores.',
506:f'Who has the greatest reputation among authors of posts linked to from posts with revision activity by {p(506,"name")!r}? Include display name and reputation.',
536:f'Which tags appear on at least {p(536,"threshold")} distinct qualifying post with revision activity by {p(536,"name")!r}? Show names and post counts.',
572:f'Which authors wrote at least {p(572,"threshold")} distinct qualifying question answered by users who joined on {p(572,"date")}? Show display names and those question counts.'
}
