"""Second separately composed held-out-instance batch."""
from .held_question_authoring import d,p,field,associated,comparison,append_batch
r102,a102,b102=comparison(102);r143,a143,b143=comparison(143);r161,a161,b161=comparison(161);r198,a198,b198=comparison(198)
q=[
f'How many points do posts by {p(100,"name")!r} average?',
f'For {p(101,"name")!r}, count comments scoring {p(101,"condition")} or above.',
f'Deduct the score total for {r102} associated with {b102} from the total for {a102}, using distinct posts separately for each named user.',
f'What average score is achieved by the different {d(103)}?',
f'I would like each post written by {p(104,"name")!r} with its {field(104)} and score.',
f'Find the strongest-scoring accepted answer to questions titled {p(105,"title")!r}; show its first 120 body characters and score.',
f'What reputation is held on average by {d(106)}?',
f'Calculate a reputation average across the distinct {d(107)}.',
f'What number of different comments is represented by {d(108)}?',
f'Show the highest-scoring comment by {p(109,"name")!r}, including its first 120 text characters and score.',
f'Total the scores for posts voted on by {p(110,"name")!r}, counting a post once.',
f'For {d(111)}, what share score above zero, as a percentage? Use all distinct posts, including those missing scores, as the denominator.',
f'Give the mean reputation of {d(112)}.',
f'How high is the greatest score of a post by holders of the {p(113,"badge")!r} badge?',
f'What do scores on comments by user {p(114,"anchor")} add up to?',
f'How few points does the least-scoring comment by {p(115,"name")!r} have?',
f'Of the distinct {d(116)}, what percentage score positively? Missing scores still belong in the denominator.',
f'For {d(117)}, compute average reputation.',
f'What score is smallest among posts voted on by {p(118,"name")!r}?',
f'Count the distinct tags meeting {d(119)}.',
f'Which tag ranks third in {d(120)} by stored usage count? Supply its name and count.',
f'User {p(121,"anchor")} has written posts; give the {field(121)} and score of the highest-scoring one.',
f'How many {d(122)} meet a reputation minimum of {p(122,"condition")}?',
f'Find the least question score within {d(123)}.',
f'For tag {p(124,"name")!r}, which wiki post scores least? Give its {field(124)} and score.',
f'How little reputation is held by the least reputable of {d(125)}?',
f'Of posts voted on by {p(126,"name")!r}, show the one with the lowest score using its {field(126)} and score.',
f'What post with revision activity by {p(127,"name")!r} has the top score? Include its {field(127)} and score.',
f'Find the largest comment score from users who joined on {p(128,"date")}.',
f'What do the scores of distinct {d(129)} sum to?',
f'Give a reputation sum over {d(130)}, counting authors once.',
f'What is the combined reputation held by {d(131)}?',
f'Total the scores reaching at least {p(132,"condition")} among {d(132)}.',
f'For {d(133)}, how much reputation is held on average?',
f'What unique {field(134)} are used for wiki posts of tag {p(134,"name")!r}? List them alphabetically.',
f'For user {p(135,"anchor")}, alphabetize the different {field(135)} of their authored posts.',
f'Give the {field(136)} and score of the best-scoring question within {d(136)}.',
f'Pick the {p(137,"k")} most-used {d(137)} using their stored usage counts; show tag names and counts.',
f'For {d(138)}, list each different post’s {field(138)} and score.',
f'How high is the best post score within {d(139)}?',
f'Show the first 120 text characters of every distinct comment in {d(140)} and its count of distinct qualifying {associated(140)}.',
f'Add scores from {d(141)} only if they are at least {p(141,"condition")}.',
f'Find the second-ranked question on score in {d(142)} and show its {field(142)} and score.',
f'Compare {a143} with {b143}: for {r143}, report the former reputation sum minus the latter, using distinct qualifying users within each named user’s total.',
f'What mean score do posts with revision activity by {p(144,"name")!r} receive?',
f'Average reputation over the different {d(145)}.',
f'Which post in {d(146)} comes first on score? Show its {field(146)} with the score.',
f'List unique answer previews for questions titled {p(147,"title")!r}, taking accepted answers’ first 120 body characters and alphabetizing them.',
f'How many separate posts with revision activity by {p(148,"name")!r} have at least one comment?',
f'Count posts in {d(149)} whose scores additionally reach {p(149,"condition")} or more.',
f'What is the mean post score for posts commented on by users who joined on {p(150,"date")}?',
f'What score total comes from comments by {p(151,"name")!r}, including only scores no lower than {p(151,"condition")}?',
f'List posts with revision activity by {p(152,"name")!r} with their {field(152)} and score.',
f'Add the scores on distinct accepted answers to questions created on {p(153,"date")}.',
f'Which post scores last among those written by holders of the {p(154,"badge")!r} badge? Show its {field(154)} and score.',
f'For questions titled {p(155,"title")!r}, give accepted answers with their first 120 body characters and score.',
f'Give the display name and reputation of the most reputable author in {d(156)}.',
f'For posts by {p(157,"name")!r}, ignore scores below {p(157,"condition")} and add the remaining scores.',
f'List the {field(158)} of {d(158)} with at least {p(158,"threshold")} distinct qualifying {associated(158)}, paired with those counts.',
f'Which post by a holder of the {p(159,"badge")!r} badge has the highest score? Give its {field(159)} and score.',
f'Show a reputation leaderboard of up to {p(160,"k")} {d(160)}, with display names and reputation.',
f'How much does the combined reputation for {r161} associated with {a161} exceed that associated with {b161}? Give a signed difference and count authors once per named user.',
f'How many points do posts by {p(162,"name")!r} hold in total?',
f'What is mean reputation within {d(163)}?',
f'Count distinct questions that holders of the {p(164,"badge")!r} badge commented on.',
f'For post {p(165,"anchor")}, list the {p(165,"k")} most reputable authors of linked posts, showing display names and reputation.',
f'Average the scores of titled posts voted on by user {p(166,"anchor")}.',
f'Of posts by holders of the {p(167,"badge")!r} badge, what percentage have a score above zero? Count distinct posts, including missing-score posts in the denominator.',
f'What maximum answer score is recorded for accepted answers to questions created on {p(168,"date")}?',
f'For the distinct {d(169)}, give the average score.',
f'What is the number of different posts scoring at least {p(170,"condition")} in {d(170)}?',
f'How many posts by {p(171,"name")!r} have no fewer than {p(171,"condition")} score points?',
f'Who ranks highest on reputation among {d(172)}? Show up to {p(172,"k")} display names and reputation.',
f'For posts commented on by users who joined on {p(173,"date")}, show the highest-scoring post’s {field(173)} and score.',
f'For {d(174)}, combine only scores of {p(174,"condition")} or higher.',
f'What reputation total remains for {d(175)} after excluding reputation below {p(175,"condition")}?',
f'Give the first 120 text characters and score of the worst-scoring comment by {p(176,"name")!r}.',
f'What distinct posts did {p(177,"name")!r} vote on? Show their {field(177)} and score.',
f'Find the lowest-scoring post in {d(178)}, including its {field(178)} and score.',
f'How many different posts are recorded as voted on by {p(179,"name")!r}?',
f'How large is the set of distinct posts linked to from posts titled {p(180,"title")!r}?',
f'Rank posts by holders of the {p(181,"badge")!r} badge on score and show the best {p(181,"k")}, including their {field(181)} and score.',
f'What is the top question score within {d(182)}?',
f'What maximum score occurs on posts commented on by {p(183,"name")!r}?',
f'What score does the best-scoring post voted on by user {p(184,"anchor")} have?',
f'Add reputation for distinct authors of questions answered by user {p(185,"anchor")}.',
f'For each of {d(186)}, give its display name and count of distinct qualifying {associated(186)}.',
f'How high is the greatest author reputation among {d(187)}?',
f'Within {d(188)}, sum scores no lower than {p(188,"condition")} once per distinct post.',
f'Which of {d(189)} have at least {p(189,"threshold")} distinct qualifying {associated(189)}? Show display names and counts.',
f'For accepted answers to questions created on {p(190,"date")}, what is the smallest score?',
f'Give the first 120 body characters and score of the answer ranking last on score among {d(191)}.',
f'Find the question with the lowest score among {d(192)}; show its {field(192)} and score.',
f'Alphabetize unique comment previews for user {p(193,"anchor")}, using the first 120 characters of text.',
f'What do the question scores within {d(194)} add up to?',
f'Show distinct posts commented on by {p(195,"name")!r}, with each {field(195)} and score.',
f'How few points does the least-scoring post written by user {p(196,"anchor")} have?',
f'Show the best {p(197,"k")} posts by users who joined on {p(197,"date")}, ranked by score, including their {field(197)} and score.',
f'For {r198}, what reputation sum for {a198} remains after subtracting the sum for {b198}? Count distinct authors separately for each named user.',
f'What is the smallest reputation recorded among authors of posts linked to from post {p(199,"anchor")}?'
]
from .held_question_edits import EDITS
q=[EDITS.get(index,sentence) for index,sentence in enumerate(q,100)]

if __name__=='__main__':append_batch(100,q)
