"""Individually authored held-out-instance questions, first batch."""
from .held_question_authoring import d,p,field,associated,comparison,append_batch
r10,a10,b10=comparison(10);r29,a29,b29=comparison(29);r67,a67,b67=comparison(67)
q=[
f'How much reputation do {d(0)} average?',
f'For tag {p(1,"name")!r}, alphabetically list the different wiki post titles, substituting the first 120 body characters when untitled.',
f'List the distinct {field(2)} for posts by user {p(2,"anchor")}, in alphabetical order.',
f'Among {d(3)}, which question has the best score? Give its {field(3)} and score.',
f'Show a ranking of the best {p(4,"k")} {d(4)} by stored usage count, including names and counts.',
f'Give each distinct linked post in {d(5)} with its {field(5)} and score.',
f'What maximum score is found among {d(6)}?',
f'List comment previews from {d(7)}, using the first 120 text characters, and the number of distinct qualifying {associated(7)} for each.',
f'For {d(8)}, how many score points remain in total after scores below {p(8,"condition")} are excluded?',
f'Find the question in third place by score among {d(9)} and show its {field(9)} and score.',
f'Total reputation for {r10} associated with {a10}, then deduct the total for {b10}. Count each qualifying user once per named user.',
f'What is mean score for posts with revision activity by {p(11,"name")!r}?',
f'On average, how much reputation belongs to {d(12)}?',
f'Which post has the highest score in {d(13)}? Include its {field(13)} and score.',
f'Give an alphabetical list of unique previews for {d(14)}, using the first 120 body characters.',
f'Count the different posts with revision activity by {p(15,"name")!r} that have comments.',
f'How many posts in {d(16)} meet a score minimum of {p(16,"condition")}?',
f'Average the scores across {d(17)}, counting each post once.',
f'Add the scores of comments by {p(18,"name")!r}, omitting any score below {p(18,"condition")}.',
f'What are the {field(19)} and score of each post with revision activity by {p(19,"name")!r}?',
f'What is the combined score for distinct {d(20)}?',
f'Find the post scoring lowest among {d(21)}; show its {field(21)} and score.',
f'Show the first 120 body characters and score for every answer in {d(22)}.',
f'Which author in {d(23)} holds the greatest reputation? Give their display name and reputation.',
f'List up to {p(24,"k")} {d(24)} with the highest reputation, giving display names and reputation.',
f'What sum of scores comes from posts by {p(25,"name")!r} scoring at least {p(25,"condition")}?',
f'Which posts in {d(26)} have at least {p(26,"threshold")} distinct qualifying {associated(26)}? Give their {field(26)} and counts.',
f'Give the {field(27)} and score of the highest-scoring post written by a holder of the {p(27,"badge")!r} badge.',
f'For {d(28)}, show the top {p(28,"k")} authors on reputation, with display names and reputation.',
f'What total reputation for {r29} associated with {a29} remains after subtracting the corresponding total for {b29}? Count authors once per named user.',
f'How many points do posts by {p(30,"name")!r} have altogether?',
f'What reputation is recorded on average for {d(31)}?',
f'How many distinct questions have been commented on by holders of the {p(32,"badge")!r} badge?',
f'Who are the most reputable {p(33,"k")} authors of posts linked to from post {p(33,"anchor")}? Give display names and reputation.',
f'What mean score do titled posts voted on by user {p(34,"anchor")} have?',
f'What percentage of distinct posts by holders of the {p(35,"badge")!r} badge have positive scores? Include missing-score posts in the denominator.',
f'For accepted answers to questions created on {p(36,"date")}, find the highest score.',
f'Calculate a mean score for the distinct {d(37)}.',
f'How many distinct posts meet {d(38)}?',
f'Count the different posts scoring at least {p(39,"condition")} among {d(39)}.',
f'How many posts authored by {p(40,"name")!r} have {p(40,"condition")} or more points?',
f'Show up to {p(41,"k")} {d(41)} with the greatest reputation, including display names and reputation.',
f'Find the top-scoring post among those commented on by users who joined on {p(42,"date")}; show its {field(42)} and score.',
f'Sum scores meeting or exceeding {p(43,"condition")} within {d(43)}.',
f'What total reputation comes from {d(44)} whose reputation is at least {p(44,"condition")}?',
f'Which comment by {p(45,"name")!r} has the smallest score? Include its first 120 text characters and score.',
f'List posts voted on by {p(46,"name")!r}, showing each distinct {field(46)} and score.',
f'For {d(47)}, identify the lowest-scoring post by its {field(47)} and score.',
f'What number of different posts has {p(48,"name")!r} voted on?',
f'Count the distinct posts linked to from posts titled {p(49,"title")!r}.',
f'Pick up to {p(50,"k")} highest-scoring posts by holders of the {p(50,"badge")!r} badge. Give their {field(50)} and score.',
f'What score is highest among questions answered by answers created on {p(51,"date")}?',
f'What score does the most highly scored post commented on by {p(52,"name")!r} have?',
f'Of posts voted on by user {p(53,"anchor")}, what is the maximum score?',
f'Combine the reputation of the different authors of questions answered by user {p(54,"anchor")}.',
f'For {d(55)}, list display names with the count of distinct qualifying {associated(55)} for each.',
f'How much reputation does the most reputable of {d(56)} hold?',
f'Total scores of at least {p(57,"condition")} for the distinct posts in {d(57)}.',
f'Show display names and counts for {d(58)} associated with at least {p(58,"threshold")} distinct qualifying {associated(58)}.',
f'What is the lowest score of an accepted answer to a question created on {p(59,"date")}?',
f'Show the lowest-scoring answer in {d(60)} as the first 120 body characters and its score.',
f'Which question scores least among {d(61)}? Give its {field(61)} and score.',
f'For user {p(62,"anchor")}, alphabetize unique comment previews taken from the first 120 text characters.',
f'Add up the scores of {d(63)}.',
f'List the distinct posts commented on by {p(64,"name")!r}, giving each {field(64)} and score.',
f'What minimum post score has user {p(65,"anchor")} earned?',
f'For users who joined on {p(66,"date")}, show up to {p(66,"k")} highest-scoring authored posts, with their {field(66)} and score.',
f'Calculate the reputation total for {r67} associated with {a67} minus that for {b67}. Deduplicate authors within each named user’s total.',
f'What is the lowest reputation held by an author of posts linked to from post {p(68,"anchor")}?',
f'What combined score do the distinct posts authored by holders of the {p(69,"badge")!r} badge have?',
f'Find the total reputation of the distinct {d(70)}.',
f'For {d(71)}, give the name and stored usage count of the highest-count tag.',
f'How many distinct questions in {d(72)} reach a score of {p(72,"condition")} or more?',
f'What stored usage count do the different tags on posts commented on by {p(73,"name")!r} average?',
f'Calculate average stored usage count for {d(74)}.',
f'Show up to {p(75,"k")} highest-scoring {d(75)}, including each {field(75)} and score.',
f'What score do {d(76)} have on average?',
f'What is the mean question score within {d(77)}?',
f'Within {d(78)}, count questions with at least {p(78,"condition")} points.',
f'What average comment score belongs to {p(79,"name")!r}?',
f'List the tags on posts by {p(80,"name")!r}, pairing tag names with counts of distinct qualifying {associated(80)}.',
f'Give the unique {field(81)} for {d(81)} in alphabetical order.',
f'How many distinct questions has user {p(82,"anchor")} voted on?',
f'How small is the lowest score among {d(83)}?',
f'Alphabetically list the distinct {field(84)} for {d(84)}.',
f'What score is greatest among posts with revision activity by {p(85,"name")!r}?',
f'Add stored usage counts for the distinct tags on posts with revision activity by {p(86,"name")!r}.',
f'What number of posts has user {p(87,"anchor")} written?',
f'For posts linked to from posts titled {p(88,"title")!r}, combine scores once per distinct post.',
f'Which names occur among {d(89)}? Give a unique alphabetical list.',
f'What total reputation is held by {d(90)}, once per author?',
f'What is average reputation across the distinct {d(91)}?',
f'Combine scores for distinct questions answered by answers created on {p(92,"date")}.',
f'What is the highest reputation among users sharing a badge with user {p(93,"anchor")}?',
f'Calculate the combined score of {d(94)}.',
f'Average scores of distinct posts voted on by {p(95,"name")!r}.',
f'What is the mean score of the distinct {d(96)}?',
f'Give the {field(97)} and score for the lowest-scoring post commented on by user {p(97,"anchor")}.',
f'Find the average score of {d(98)}, using each post once.',
f'Which posts in {d(99)} have at least {p(99,"threshold")} distinct qualifying {associated(99)}? List their {field(99)} and counts.'
]
from .held_question_edits import EDITS
q=[EDITS.get(index,sentence) for index,sentence in enumerate(q,0)]

if __name__=='__main__':append_batch(0,q)
