"""Second structure batch; each selected instance has its own wording."""
from .held_question_authoring import d,p,field,associated,comparison,append_batch
r400,a400,b400=comparison(400);r401,a401,b401=comparison(401);r402,a402,b402=comparison(402);r403,a403,b403=comparison(403)
q=[
f'For authors of accepted answers to questions titled {p(364,"title")!r}, what average score do their distinct comments created from {p(364,"year")} through {p(364,"end_year")} inclusive have?',
f'Average scores of comments created in years {p(365,"year")} through {p(365,"end_year")} inclusive by authors of accepted answers to questions titled {p(365,"title")!r}.',
f'Questions titled {p(366,"title")!r} have accepted-answer authors. Among their distinct comments written from {p(366,"year")} through {p(366,"end_year")} inclusive, what is mean score?',
f'What is the mean score of comments written in {p(367,"year")} by authors of accepted answers to questions titled {p(367,"title")!r}, counting comments once?',
f'What score total comes from comments without saved author display names by authors of accepted answers to questions titled {p(368,"title")!r}? Count each comment once.',
f'For questions titled {p(369,"title")!r}, take accepted-answer authors and their comments lacking a saved author display name. Add the scores of those distinct comments.',
f'Combine scores from comments by accepted-answer authors for questions titled {p(370,"title")!r}, including only comments without recorded saved author display names.',
f'How many score points do comments with no saved author display name contribute altogether when written by authors of accepted answers to questions titled {p(371,"title")!r}? Deduplicate comments.',
f'What stored usage count is smallest among tags on posts with revision activity by {p(372,"name")!r}?',
f'For {p(373,"name")!r}, consider tags on posts with their revision activity. Give the lowest stored usage count.',
f'Find the minimum stored usage count in tags appearing on posts with revision activity by {p(374,"name")!r}.',
f'How low does stored usage count go for tags on posts where {p(375,"name")!r} has revision activity?',
f'For question {p(376,"anchor")}, find accepted-answer authors and tags on their posts. What stored usage count is highest among those tags?',
f'What is the greatest stored usage count of any of {d(377)}?',
f'How high is the maximum stored usage count across tags on posts by authors of accepted answers to question {p(378,"anchor")}?',
f'Find the largest stored usage count among the tags in {d(379)}.',
f'What is the total stored usage count of {d(380)} if only counts of at least {p(380,"condition")} contribute?',
f'Sum the stored usage counts reaching {p(381,"condition")} or more within {d(381)}.',
f'For {d(382)}, leave out counts below {p(382,"condition")}. What is the remaining stored usage count total?',
f'Add counts of no less than {p(383,"condition")} from {d(383)}; what does that give?',
f'How many authors whose display names begin with {p(384,"text")!r} wrote posts linked to from posts with revision activity by users who joined on {p(384,"date")}? Match case and count authors once.',
f'For users who joined on {p(385,"date")}, consider posts with their revision activity and posts linked from those. Count distinct linked-post authors with display names starting with {p(385,"text")!r}, case-sensitively.',
f'What number of different authors satisfies {d(386)}?',
f'Count authors of posts linked to from posts with revision activity by users joining on {p(387,"date")}, keeping only display names prefixed by {p(387,"text")!r} with exact capitalization.',
f'Who ranks second by reputation among {d(388)}? Show the display name and reputation.',
f'For {d(389)}, name the runner-up in reputation and give their reputation.',
f'Show the display name and reputation of the user in fifth place when {d(390)} are ordered by decreasing reputation.',
f'Which of {d(391)} is fifth most reputable? Include their display name and reputation.',
f'Find the tag with the highest stored usage count among {d(392)} and show its name and count.',
f'For questions titled {p(393,"title")!r}, find accepted-answer authors and tags on their posts. Show the highest-count tag by stored usage, including its name and count.',
f'Which tag leads {d(394)} by stored usage count? Give its name and count.',
f'Give the name and stored usage count of the most-used tag in {d(395)}.',
f'How many distinct tags in {d(396)} satisfy the stated case-sensitive prefix?',
f'For questions titled {p(397,"title")!r}, take accepted-answer authors and their posts. Count distinct tags on those posts whose names start with {p(397,"text")!r}, matching case exactly.',
f'What number of tags satisfies {d(398)}, without counting a tag twice?',
f'Count different tag names beginning with {p(399,"text")!r}, case-sensitively, on posts by authors of accepted answers to questions titled {p(399,"title")!r}.',
f'For {r400}, calculate the score total associated with {a400} less the total associated with {b400}, counting each comment once per named user.',
f'What signed difference, {a401} minus {b401}, separates the combined scores of {r401}? Deduplicate comments within each named user’s total.',
f'Add scores of {r402} associated with {a402} and subtract the corresponding sum for {b402}, using each distinct comment once per named user.',
f'Compare {a403} and {b403} on score totals for {r403}. Give the first total minus the second, treating comments as distinct within each total.',
f'How many {d(404)} have stored usage counts of at least {p(404,"condition")}?',
f'Within {d(405)}, count tags meeting a stored usage count minimum of {p(405,"condition")}.',
f'What number of {d(406)} additionally have at least {p(406,"condition")} recorded uses?',
f'For {d(407)}, how large is the set of tags whose stored usage count reaches {p(407,"condition")} or more?',
f'Which posts have at least {p(408,"threshold")} distinct revision entries by {p(408,"name")!r}? Show their {field(408)} and revision-entry counts for that user.',
f'List posts with {p(409,"threshold")} or more distinct revision entries made by {p(409,"name")!r}, giving each {field(409)} and the qualifying count.',
f'For {p(410,"name")!r}, show the {field(410)} and distinct revision-entry count of posts with at least {p(410,"threshold")} of their revision entries.',
f'Find posts on which {p(411,"name")!r} made at least {p(411,"threshold")} distinct revision entries; include each {field(411)} and count.',
f'For {d(412)}, what average score do the distinct comments have? The year bounds apply to the comments themselves.',
f'Users joining on {p(413,"date")} authored posts that link to other posts. Average scores of comments written in {p(413,"year")} by those linked posts’ authors, counting comments once.',
f'What mean score belongs to comments created in {p(414,"year")} by authors of posts linked to from posts by users who joined on {p(414,"date")}?',
f'Consider authors of posts linked to from posts by users joining on {p(415,"date")}. What do their distinct comments created from {p(415,"year")} through {p(415,"end_year")} inclusive average in score?',
f'How many posts commented on by holders of the {p(416,"badge")!r} badge have titles containing {p(416,"text")!r}, case-sensitively?',
f'Count the distinct posts with {p(417,"text")!r} in their title, matching case, that holders of the {p(417,"badge")!r} badge commented on.',
f'For the {p(418,"badge")!r} badge, what number of posts its holders commented on have a title containing {p(418,"text")!r} with exact capitalization?',
f'List the names of {d(419)} and count the distinct qualifying posts carrying each tag.',
f'For questions titled {p(420,"title")!r}, find accepted-answer authors and their posts. Give tag names with counts of the distinct posts by those authors on which each tag occurs.',
f'Break down {d(421)} by their distinct qualifying post counts. Show tag names and counts.',
f'For each distinct tag in {d(422)}, show its name and how many qualifying posts use it.',
f'Which tags occur on at least {p(423,"threshold")} distinct qualifying posts in {d(423)}? Give names and counts.',
f'For questions titled {p(424,"title")!r}, take accepted-answer authors and their posts. List tags used on at least {p(424,"threshold")} distinct posts in that set, showing tag names and counts.',
f'Find tags in {d(425)} with at least {p(425,"threshold")} distinct qualifying posts; include names and post counts.',
f'Give tag names and counts for {d(426)} carried by at least {p(426,"threshold")} distinct qualifying posts.',
f'List wiki posts for tag {p(427,"anchor")}, showing each {field(427)} and score.',
f'For tag {p(428,"anchor")}, give the wiki posts with their {field(428)} and score.',
f'What wiki posts belong to tag {p(429,"anchor")}? Show their {field(429)} alongside score.',
f'I need the {field(430)} and score of each wiki post for tag {p(430,"anchor")}.',
f'Rank {d(431)} by stored usage count and show up to {p(431,"k")} highest-count tags, including names and counts.',
f'For {d(432)}, which {p(432,"k")} tags have the greatest stored usage counts? List their names and counts.',
f'Give a leaderboard of up to {p(433,"k")} {d(433)} based on stored usage count, with tag names and counts.',
f'Among {d(434)}, select the {p(434,"k")} most-used tags according to stored counts. Show names and counts.',
f'How many distinct posts meet {d(435)}?',
f'For posts titled {p(436,"title")!r}, take authors of linked posts and the posts they commented on. Count distinct commented-on posts with a case-sensitive {p(436,"text")!r} in the title.',
f'What number of different posts satisfies {d(437)}?',
f'Count the distinct posts in {d(438)} that meet the title substring condition.',
f'Find the lowest-count tag by stored usage among {d(439)}, with its name and count.',
f'For {d(440)}, which tag has the least stored usage count? Show its name and count.',
f'Give the name and stored usage count of the least-used tag in {d(441)}.',
f'What tag comes last on stored usage count among {d(442)}? Include its name and count.',
f'How many posts voted on by {p(443,"name")!r} have a title containing {p(443,"text")!r}, with exact capitalization?',
f'Count distinct posts whose titles contain the case-sensitive text {p(444,"text")!r} among posts voted on by {p(444,"name")!r}.',
f'For {p(445,"name")!r}, what number of voted-on posts contain {p(445,"text")!r} in their title, matching case?',
f'What count of different posts meets {d(446)}?',
f'How many distinct uncommented posts were written by holders of the {p(447,"badge")!r} badge?',
f'Count posts by holders of the {p(448,"badge")!r} badge that have no comments, using each post once.',
f'For holders of the {p(449,"badge")!r} badge, what number of authored posts remains without comments?',
f'What is the count of different posts written by holders of the {p(450,"badge")!r} badge with no comments at all?',
f'What is the minimum stored usage count of tags on posts by {p(451,"name")!r}?',
f'{p(452,"name")!r} authored posts with tags. Find the smallest stored usage count among those tags.',
f'Of tags used on posts by {p(453,"name")!r}, how low is the least stored usage count?',
f'For posts written by {p(454,"name")!r}, give the lowest stored usage count across their tags.',
f'How many posts with revision activity by user {p(455,"anchor")} have titles containing {p(455,"text")!r}? Use case-sensitive matching.',
f'Count distinct posts with a case-sensitive {p(456,"text")!r} in the title that user {p(456,"anchor")} has revision activity on.',
f'For user {p(457,"anchor")}, what number of posts with their revision activity contain {p(457,"text")!r} in the title with exact capitalization?',
f'What is the count of different posts satisfying {d(458)}?',
f'Among {d(459)}, what stored usage count is lowest?',
f'For question {p(460,"anchor")}, find accepted-answer authors and tags on their posts. Give the smallest stored usage count of those tags.',
f'How low does stored usage count go across tags on posts by authors of accepted answers to question {p(461,"anchor")}?',
f'Find the minimum stored usage count within {d(462)}.',
f'How many distinct tags in {d(463)} meet the case-sensitive substring condition?'
]
from .held_question_edits import EDITS
q=[EDITS.get(index,sentence) for index,sentence in enumerate(q,364)]

if __name__=='__main__':append_batch(364,q)
