"""Fourth batch of individually written questions."""
from .question_authoring import d,m,p,field,associated,comparison,append_batch
r300,x300,y300=comparison(300);r338,x338,y338=comparison(338);r374,x374,y374=comparison(374)
q=[
f'Using distinct authors for each named user, total reputation for {r300} associated with {x300} and subtract the total associated with {y300}.',
f'For {d(301)}, what is the sum of all post scores?',
f'How much reputation do users average within {d(302)}?',
f'How many unique questions occur among {d(303)}?',
f'Who ranks in the top {p(304,"k")} of {d(304)} by reputation? Give display names and reputation.',
f'Compute the average score over {d(305)}, once per post.',
f'Express as a percentage the share of distinct {d(306)} with scores above zero; the denominator includes posts with missing scores.',
f'How high is the top score among {d(307)}?',
f'What is the mean score across the distinct {d(308)}?',
f'How many different posts satisfy the prefix condition in {d(309)}?',
f'What count of distinct posts scoring at least {p(310,"condition")} comes from {d(310)}?',
f'Count posts with {p(311,"condition")} or more points in {d(311)}.',
f'Rank {d(312)} by reputation. Show the top {p(312,"k")} display names and reputation.',
f'I am looking for the highest-scoring post among {d(313)}. Give its {field(313)} and score.',
f'What is the score sum across {d(314)} if scores below {p(314,"condition")} contribute nothing?',
f'For {d(315)}, include only reputation of at least {p(315,"condition")} in a combined reputation total.',
f'Show the lowest-scoring comment from {d(316)} as the first 120 characters of text, with its score.',
f'What are the {field(317)} and score for the different {d(317)}?',
f'Among {d(318)}, find the post with the smallest score and show its {field(318)} and score.',
f'Count how many distinct posts are represented by {d(319)}.',
f'How many posts does {d(320)} contain after deduplication?',
f'Who has the best posts? List up to {p(321,"k")} highest-scoring {d(321)} with their {field(321)} and scores.',
f'What score is greatest among the questions in {d(322)}?',
f'How many points does the most highly scored post in {d(323)} have?',
f'Find the maximum post score within {d(324)}.',
f'Give the total reputation of {d(325)}, taking each distinct author once.',
f'List the display names of {d(326)} and the number of distinct qualifying {associated(326)} for each author.',
f'Among {d(327)}, what reputation is highest?',
f'Add up scores from {d(328)} only when they are at least {p(328,"condition")}.',
f'Give display names and counts for {d(329)} with at least {p(329,"threshold")} distinct qualifying {associated(329)}.',
f'What minimum answer score is found in {d(330)}?',
f'Which answer ranks lowest by score in {d(331)}? I need a preview of its first 120 body characters and the score.',
f'For {d(332)}, give the {field(332)} and score of the question with the smallest score.',
f'Give me an alphabetical set of unique comment previews from {d(333)}, using the first 120 text characters.',
f'What is the score total of all {d(334)}?',
f'Show each different {d(335)} by its {field(335)} and score.',
f'How many points does the least highly scored post in {d(336)} have?',
f'What are the best {p(337,"k")} {d(337)} by score? Include their {field(337)} and scores.',
f'Calculate the total reputation for {r338} associated with {x338}, minus that for {y338}. Count each qualifying author once per named user.',
f'Find the minimum reputation of {d(339)}.',
f'How many points do {d(340)} have in total, counting each post once?',
f'For {d(341)}, calculate their combined reputation without repeating an author.',
f'Identify the tag with the greatest stored usage count among {d(342)} and give its name and count.',
f'How many distinct questions scoring {p(343,"condition")} or more occur in {d(343)}?',
f'How high is the mean stored usage count for the distinct {d(344)}?',
f'Average stored usage counts across {d(345)}.',
f'For {d(346)}, show the winning comment by score, as the first 120 characters of text and its score.',
f'Give up to {p(347,"k")} best-scoring {d(347)}, with the {field(347)} and score of each.',
f'On average, how many points do {d(348)} have?',
f'What score is typical on average for {d(349)}?',
f'Within {d(350)}, count questions whose scores are not below {p(350,"condition")}.',
f'Compute an average from the scores of {d(351)}.',
f'Give tag names for {d(352)}, with counts of the distinct qualifying {associated(352)} carrying each tag.',
f'I need unique {field(353)} from {d(353)}, listed alphabetically.',
f'What number of different questions are in {d(354)}?',
f'Of {d(355)}, how low is the smallest score?',
f'List each different {field(356)} for {d(356)} in alphabetical order.',
f'What is the maximum score on {d(357)}?',
f'Total the stored usage counts associated with the distinct {d(358)}.',
f'Count posts in {d(359)}, using one count per distinct post.',
f'What do the scores on the different {d(360)} total?',
f'Show the names of {d(361)} in alphabetical order, with each name appearing just once.',
f'What aggregate reputation belongs to {d(362)}? Take each distinct author once.',
f'Average the reputation of the different {d(363)}.',
f'What do the scores for distinct questions in {d(364)} sum to?',
f'For {d(365)}, find the greatest reputation.',
f'Add up every post score in {d(366)}.',
f'How high is mean score for the distinct {d(367)}?',
f'For the different {d(368)}, give their mean score.',
f'Find the worst-scoring post among {d(369)} and supply its {field(369)} and score.',
f'What is the mean post score within {d(370)}?',
f'Which posts in {d(371)} are associated with at least {p(371,"threshold")} distinct qualifying {associated(371)}? List their {field(371)} and counts.',
f'Average the scores of the posts in {d(372)}.',
f'How many comments from {d(373)} score at least {p(373,"condition")}?',
f'Determine the score total for {r374} associated with {x374} and deduct the total for {y374}; count each post once per named user.',
f'How many points do the distinct {d(375)} average?',
f'I want the {field(376)} and score of every post in {d(376)}.',
f'What accepted answer comes first by score among {d(377)}? Give the first 120 body characters and score.',
f'For the distinct {d(378)}, how much reputation do they average?',
f'Calculate the average reputation of authors in {d(379)}.',
f'How many different comments are included in {d(380)}?',
f'Which comment in {d(381)} has the top score? Include a preview of its first 120 text characters and that score.',
f'What sum of post scores belongs to {d(382)}, once per distinct post?',
f'Calculate the percentage of distinct {d(383)} scoring above zero; missing-score posts still count in the denominator.',
f'How high is average reputation among {d(384)}?',
f'What score is the largest within {d(385)}?',
f'Combine all the scores of {d(386)}.',
f'What score does the weakest-scoring comment in {d(387)} have?',
f'Of all distinct {d(388)}, what percentage score above zero? Include those without a recorded score in the population.',
f'Find the mean reputation across {d(389)}.',
f'How small is the minimum score among {d(390)}?',
f'What count of distinct tags satisfies {d(391)}?',
f'Which tag comes second in {d(392)} when ranked by stored usage count? Show its name and count.',
f'Find the strongest-scoring post in {d(393)} and give its {field(393)} and score.',
f'Among {d(394)}, what number have reputation of at least {p(394,"condition")}?',
f'What score is lowest among {d(395)}?',
f'I need the least-scoring wiki post in {d(396)}, identified by its {field(396)}, with its score.',
f'How little reputation does the least reputable author in {d(397)} have?',
f'Which post scores least among {d(398)}? Include its {field(398)} and score.',
f'Select the best-scoring post from {d(399)} and show its {field(399)} with the score.'
]
if __name__=='__main__':append_batch(300,q)
