"""Separately authored questions, third checkpoint batch."""
from .question_authoring import d,m,p,field,associated,comparison,append_batch
r203,x203,y203=comparison(203);r239,x239,y239=comparison(239);r280,x280,y280=comparison(280)
q=[
f'Could you show the different {d(200)} with each {field(200)} and score?',
f'What score does the lowest-scoring post among {d(201)} have?',
f'For {d(202)}, give up to {p(202,"k")} posts at the top of the score ranking, with their {field(202)} and score.',
f'I want a difference in aggregate reputation: total it for {r203} associated with {x203}, then subtract the total for {y203}. Count each author once per named user.',
f'How little reputation does the least reputable of {d(204)} have?',
f'What is the total of scores belonging to {d(205)}, counting posts once?',
f'What is the combined reputation of the distinct authors in {d(206)}?',
f'Give the name and stored usage count of the leading tag among {d(207)}.',
f'For {d(208)}, how many distinct questions meet a score threshold of {p(208,"condition")} or more?',
f'Average the stored usage counts of the different {d(209)}.',
f'For {d(210)}, what is the mean stored usage count?',
f'Which comment wins on score among {d(211)}? Include a preview of the first 120 text characters and the score.',
f'Select the best {p(212,"k")} {d(212)} by score and give their {field(212)} and scores.',
f'Across {d(213)}, what is the mean score?',
f'How many points do {d(214)} average?',
f'What number of {d(215)} meet the additional requirement of scoring at least {p(215,"condition")}?',
f'What is the mean of the scores for {d(216)}?',
f'List {d(217)} by tag name, paired with the count of distinct qualifying {associated(217)} for each.',
f'What are the different {field(218)} for {d(218)}? Put the list in alphabetical order.',
f'Give a count of the distinct {d(219)}.',
f'What score is smallest within {d(220)}?',
f'Show {d(221)} as an alphabetical list of distinct {field(221)}.',
f'What score does the best-scoring post in {d(222)} have?',
f'Add up the stored usage counts for all distinct {d(223)}.',
f'What is the size of the set of different {d(224)}?',
f'For {d(225)}, calculate a score sum using each post only once.',
f'I would like the distinct tag names for {d(226)}, alphabetized.',
f'How much reputation is held in total by {d(227)}, once per distinct author?',
f'Among {d(228)}, calculate mean reputation.',
f'Combine the scores of the distinct questions in {d(229)}.',
f'What reputation does the leading user among {d(230)} have?',
f'What score total results from {d(231)}?',
f'Find the mean of post scores for {d(232)}, avoiding duplicate posts.',
f'How high is the average score of {d(233)}, once per linked post?',
f'Locate the least highly scored post in {d(234)}. Show the {field(234)} and score.',
f'What average score is recorded across {d(235)}?',
f'List the {field(236)} for {d(236)} with at least {p(236,"threshold")} distinct qualifying {associated(236)}, together with the counts.',
f'What score do posts average in {d(237)}?',
f'How many different {d(238)} reach {p(238,"condition")} points or more?',
f'For {r239}, compare {x239} and {y239} on score totals. Give the first minus the second, counting distinct posts separately for each named user.',
f'For {d(240)}, how high is their mean score?',
f'Give me the posts in {d(241)} with their {field(241)} and score, once per post.',
f'Show the accepted answer with the highest score in {d(242)}. Include the first 120 body characters and score.',
f'What is mean reputation among {d(243)}?',
f'Average the reputation across the different authors in {d(244)}.',
f'What count do you get for the different {d(245)}?',
f'Which of {d(246)} has the greatest score? Return the first 120 comment text characters and that score.',
f'How many points do the distinct {d(247)} have altogether?',
f'What fraction, expressed as a percentage, of distinct {d(248)} score positively? Keep missing-score posts in the denominator.',
f'Give the average reputation among {d(249)}.',
f'How high is the best post score in {d(250)}?',
f'Add the scores from all {d(251)}.',
f'What is the least comment score among {d(252)}?',
f'For {d(253)}, what share have positive scores? Give a percentage based on all distinct posts, including posts missing a score.',
f'What reputation do {d(254)} average?',
f'Find the minimum post score within {d(255)}.',
f'Count the different tag names represented by {d(256)}.',
f'For {d(257)}, identify the tag ranked third by stored usage count and show its name and count.',
f'I want the best-scoring post in {d(258)} identified by its {field(258)}, with its score.',
f'What is the number of {d(259)} whose reputation reaches at least {p(259,"condition")}?',
f'Among {d(260)}, what is the lowest question score?',
f'Give the {field(261)} and score of the wiki post scoring least among {d(261)}.',
f'What is the lowest author reputation among {d(262)}?',
f'For {d(263)}, identify the lowest-scoring post by its {field(263)} and show the score.',
f'What post scores highest within {d(264)}? I need its {field(264)} and score.',
f'How high does the score of {d(265)} get?',
f'What score sum comes from the distinct {d(266)}?',
f'Add up reputation for {d(267)}, using each author once.',
f'Calculate the combined reputation of {d(268)}.',
f'What total remains when you sum only scores of at least {p(269,"condition")} from {d(269)}?',
f'Calculate the mean reputation for {d(270)}.',
f'Alphabetize the different {field(271)} for {d(271)} and list each once.',
f'For {d(272)}, show distinct {field(272)} in alphabetical order.',
f'Give the {field(273)} and score for the highest-scoring question among {d(273)}.',
f'Which {p(274,"k")} {d(274)} rank highest by stored usage count? Show their names and counts.',
f'Can I see {d(275)}, each with its {field(275)} and score?',
f'What is the best score recorded among {d(276)}?',
f'For each distinct comment among {d(277)}, give its first 120 text characters and how many distinct qualifying {associated(277)} it has.',
f'What is the combined score of {d(278)} with scores no lower than {p(278,"condition")}?',
f'Which question comes fifth when {d(279)} are ranked by descending score? Show its {field(279)} and score.',
f'Compare the reputation totals for {r280} between {x280} and {y280}; report the first less the second, counting each qualifying user once per named user.',
f'Find the mean score on the distinct {d(281)}.',
f'What reputation do the distinct authors in {d(282)} average?',
f'Locate the post with the greatest score among {d(283)} and give its {field(283)} and score.',
f'What unique answer previews come from {d(284)}? List the first 120 body characters alphabetically.',
f'How many unique posts are in {d(285)}?',
f'Count {d(286)} scoring {p(286,"condition")} or higher.',
f'What average post score is found in {d(287)}?',
f'Compute a score total for {d(288)}, leaving out scores below {p(288,"condition")}.',
f'I need a list of {d(289)} with the {field(289)} and score of each distinct post.',
f'Total the scores associated with {d(290)}, counting an answer just once.',
f'What is the lowest-ranked post by score among {d(291)}? Give its {field(291)} and score.',
f'List {d(292)} with an answer preview of the first 120 body characters and its score.',
f'Among {d(293)}, identify the user with the largest reputation, including their display name and reputation.',
f'Show the {p(294,"k")} most reputable {d(294)}, including display names and reputation.',
f'Sum scores of at least {p(295,"condition")} for {d(295)}; what is the total?',
f'Which {d(296)} have at least {p(296,"threshold")} distinct qualifying {associated(296)}? Show their {field(296)} and counts.',
f'For {d(297)}, which post ranks first by score? Include its {field(297)} and score.',
f'List {d(298)} with at least {p(298,"threshold")} distinct qualifying {associated(298)}, giving their display names and those totals.',
f'I need up to {p(299,"k")} highest-reputation {d(299)} with display names and reputation.'
]
if __name__=='__main__':append_batch(200,q)
