"""Individually composed training questions, batch two."""
from .question_authoring import d,m,p,field,associated,comparison,append_batch
r104,x104,y104=comparison(104);r145,x145,y145=comparison(145);r165,x165,y165=comparison(165)
q=[
f'Average the scores of {d(100)}, counting each qualifying post once.',
f'Which of {d(101)} have at least {p(101,"threshold")} distinct qualifying {associated(101)}? Give their {field(101)} and the count for each.',
f'How high is the average score for {d(102)}?',
f'Count the distinct {d(103)} with scores no lower than {p(103,"condition")}.',
f'What is the combined score for {r104} associated with {x104}, less the corresponding total for {y104}? Deduplicate posts separately for each named user.',
f'What mean score belongs to {d(105)}?',
f'List {d(106)}. For each post give its {field(106)} and score.',
f'Which accepted answer tops {d(107)} on score? Show the first 120 body characters and its score.',
f'Calculate average reputation for {d(108)}.',
f'What reputation do {d(109)} have on average?',
f'How many distinct comments are among {d(110)}?',
f'I want the first 120 text characters and score of the best-scoring comment among {d(111)}.',
f'What total score do the different {d(112)} account for?',
f'Among the distinct {d(113)}, what percentage have positive scores? Treat missing scores as nonpositive but keep them in the total population.',
f'Average the reputation of {d(114)}.',
f'What is the highest post score among {d(115)}?',
f'What do the scores of {d(116)} sum to?',
f'Find the lowest score of any of {d(117)}.',
f'How large a percentage of the distinct {d(118)} have scores greater than zero, retaining missing scores in the denominator?',
f'For {d(119)}, report mean reputation.',
f'What is the lowest score in {d(120)}?',
f'How many different {d(121)} are there?',
f'Which of {d(122)} ranks third by stored usage count? Show the tag name and count.',
f'Give the {field(123)} and score of the highest-scoring post among {d(123)}.',
f'How many {d(124)} have reputation of at least {p(124,"condition")}?',
f'What is the smallest score for questions answered by the answer with ID {p(125,"anchor")}?',
f'Find the least highly scored wiki post among {d(126)}; include its {field(126)} and score.',
f'Among {d(127)}, how small is the minimum reputation?',
f'Who or what scored lowest? For {d(128)}, show that post’s {field(128)} and score.',
f'Which post has the largest score in {d(129)}? Include its {field(129)}.',
f'What maximum score is recorded for {d(130)}?',
f'Sum the scores for {d(131)}, once per post.',
f'How much reputation do the distinct {d(132)} hold in total?',
f'What is the reputation total across {d(133)}?',
f'Only count scores of at least {p(134,"condition")}: what score total comes from {d(134)}?',
f'For {d(135)}, what is the mean reputation?',
f'What distinct {field(136)} occur among {d(136)}? List them alphabetically.',
f'Show an alphabetical, deduplicated list of the {field(137)} for {d(137)}.',
f'Out of {d(138)}, show the {field(138)} and score of the one with the greatest score.',
f'Order {d(139)} by stored usage count and show the top {p(139,"k")} tag names with those counts.',
f'For every distinct post in {d(140)}, give its {field(140)} alongside its score.',
f'Of all {d(141)}, what score is highest?',
f'Show a comment preview for each of {d(142)}, using the first 120 text characters, and its count of distinct qualifying {associated(142)}.',
f'For {d(143)}, ignore scores below {p(143,"condition")} and total the rest, once per answer.',
f'Find the second highest-scoring question in {d(144)}; return its {field(144)} and score.',
f'How does combined reputation for {r145} differ between {x145} and {y145}? Give the first total minus the second and count each qualifying user once per named user.',
f'What is the average of the scores on {d(146)}?',
f'Find the average reputation of the distinct {d(147)}.',
f'I need the winning post in {d(148)} by score, with its {field(148)} and score.',
f'Show unique answer previews from {d(149)}, in alphabetical order. Use the first 120 characters of each body.',
f'What number of distinct {d(150)} can be found?',
f'How many {d(151)} score at least {p(151,"condition")}?',
f'Calculate a mean score across the distinct {d(152)}.',
f'Add together all scores at least {p(153,"condition")} for {d(153)}.',
f'Show each distinct item in {d(154)} with its {field(154)} and score.',
f'Combine the scores from {d(155)}, without counting any answer twice.',
f'Of {d(156)}, which has the minimum score? Supply its {field(156)} and that score.',
f'I would like {d(157)}, each with a preview of the first 120 body characters and its score.',
f'Who has the highest reputation among {d(158)}? Give the display name and reputation.',
f'List up to {p(159,"k")} {d(159)} in decreasing reputation order, with display names and reputation.',
f'If posts scoring below {p(160,"condition")} are excluded, what is the remaining score sum for {d(160)}?',
f'Find {d(161)} with at least {p(161,"threshold")} distinct qualifying {associated(161)}. Show each {field(161)} and its count.',
f'What is the {field(162)} and score of the most highly scored post in {d(162)}?',
f'Give the display names of {d(163)} associated with at least {p(163,"threshold")} distinct qualifying {associated(163)} and the corresponding counts.',
f'From {d(164)}, select the {p(164,"k")} highest-reputation users and give display names and reputation.',
f'Subtract the total reputation for {r165} associated with {y165} from that associated with {x165}. Count each author once for each named user.',
f'How much score do {d(166)} contribute altogether?',
f'How high is mean reputation within {d(167)}?',
f'What is the count of distinct {d(168)}?',
f'Give a reputation ranking of the best {p(169,"k")} {d(169)}, showing their display names and reputation.',
f'What is the mean score of the different {d(170)}?',
f'Among {d(171)}, how many percent score above zero? Use all distinct posts, including those without recorded scores, as the denominator.',
f'Tell me the highest answer score in {d(172)}.',
f'What score do {d(173)} have on average, counting each post once?',
f'What is the number of different {d(174)}?',
f'Count how many distinct {d(175)} reach a score of {p(175,"condition")} or higher.',
f'How many distinct posts among {d(176)} have at least {p(176,"condition")} points?',
f'Who are the best {p(177,"k")} {d(177)} by reputation? Show display names and their reputation.',
f'For {d(178)}, name the highest-scoring post using its {field(178)} and give its score.',
f'Find a total for the scores of {d(179)} that are at least {p(179,"condition")}.',
f'Add the reputation of {d(180)} with reputation no lower than {p(180,"condition")}.',
f'Which comment ranks last on score among {d(181)}? Include its first 120 text characters and score.',
f'For {d(182)}, list each distinct post’s {field(182)} and score.',
f'Show the post at the bottom of {d(183)} by score, including its {field(183)} and score.',
f'How many different posts are in {d(184)}?',
f'Count the separate posts in {d(185)}, excluding repeated occurrences of a post.',
f'Give up to {p(186,"k")} highest-scoring {d(186)} with their {field(186)} and scores.',
f'How many points does the highest-scoring question among {d(187)} have?',
f'Find the largest post score for {d(188)}.',
f'What is the top score seen in {d(189)}?',
f'Calculate a reputation sum for the distinct {d(190)}.',
f'Break down {d(191)} by their numbers of distinct qualifying {associated(191)}. List each display name with that count.',
f'What reputation does the most reputable author in {d(192)} have?',
f'For {d(193)}, what do scores of at least {p(193,"condition")} add up to?',
f'Which of {d(194)} have at least {p(194,"threshold")} distinct qualifying {associated(194)}? Supply display names and counts.',
f'Find the least score recorded for {d(195)}.',
f'Give the first 120 body characters of the lowest-scoring answer among {d(196)}, together with its score.',
f'What question ranks lowest in {d(197)} by score? Show its {field(197)} and score.',
f'What different comment previews occur in {d(198)}? Alphabetize the first 120 text characters and remove duplicates.',
f'Total the scores of {d(199)}.'
]
if __name__=='__main__':append_batch(100,q)
