"""One hundred separately composed questions; no sentence-generation templates."""
from .question_authoring import d,m,p,field,associated,comparison,append_batch

a,b,c=comparison(10); a30,b30,c30=comparison(30);a68,b68,c68=comparison(68)
q=[
f'What average reputation do {d(0)} have?',
f'List the distinct {field(1)} for {d(1)}, alphabetically.',
f'I only need a unique alphabetical list of the {field(2)} for {d(2)}.',
f'Which of {d(3)} scores highest? Give its {field(3)} and score.',
f'Name the top {p(4,"k")} {d(4)} by stored usage count, with their counts.',
f'Show the {field(5)} and score for each of {d(5)}.',
f'How high is the best score among {d(6)}?',
f'For {d(7)}, list the comment previews and count the distinct qualifying {associated(7)} for each.',
f'Add the scores of {d(8)} that score at least {p(8,"condition")}; what total results?',
f'What is the third highest-scoring item among {d(9)}? Include its {field(9)} and score.',
f'For {a}, subtract the combined reputation for {c} from that for {b}; count each user once per named user.',
f'I would like the mean score of {d(11)}.',
f'Calculate average reputation across the different {d(12)}.',
f'Find the highest-scoring item among {d(13)} and show its {field(13)} alongside its score.',
f'Give an alphabetical list of distinct answer previews for {d(14)}. Each preview should contain the first 120 body characters.',
f'How many different {d(15)} are there?',
f'Of {d(16)}, how many have a score of at least {p(16,"condition")}?',
f'What score do {d(17)} average?',
f'For {d(18)}, total only scores greater than or equal to {p(18,"condition")}.',
f'I need the {field(19)} and score of each distinct item among {d(19)}.',
f'What combined score comes from {d(20)}, counting each answer once?',
f'Which of {d(21)} has the lowest score? Show its {field(21)} and score.',
f'Could you list {d(22)} with the first 120 characters of each answer body and its score?',
f'Identify the most reputable user among {d(23)}; include the display name and reputation.',
f'Give me {p(24,"k")} highest-reputation {d(24)}, with display names and reputation.',
f'What is the score total for {d(25)} if only posts scoring at least {p(25,"condition")} contribute?',
f'List the {field(26)} of {d(26)} associated with at least {p(26,"threshold")} distinct qualifying {associated(26)}; include the counts.',
f'Among {d(27)}, pick the highest-scoring post and give its {field(27)} and score.',
f'Which of {d(28)} are associated with at least {p(28,"threshold")} distinct qualifying {associated(28)}? Show display names and those counts.',
f'Who are the top {p(29,"k")} {d(29)} by reputation? Include their display names and reputation.',
f'Compare {b30} with {c30} on total reputation of {a30}. Report the first total minus the second, once per distinct author per named user.',
f'Add up the scores of the distinct {d(31)}.',
f'What is the mean reputation of {d(32)}?',
f'Count the different {d(33)}.',
f'Rank {d(34)} by reputation and show the best {p(34,"k")}, including display names and reputation.',
f'Find the average score for {d(35)}.',
f'What percentage of the distinct {d(36)} score above zero? Include posts with missing scores in the denominator.',
f'What is the greatest score achieved by {d(37)}?',
f'For {d(38)}, give the average score, once per post.',
f'How many different {d(39)} match?',
f'Among {d(40)}, count the distinct posts with scores of at least {p(40,"condition")}.',
f'How many of {d(41)} score {p(41,"condition")} or more?',
f'Show the {p(42,"k")} most reputable {d(42)} with their display names and reputation.',
f'Which post leads {d(43)} on score? I need its {field(43)} and score.',
f'Sum the scores of {d(44)}, including only scores at or above {p(44,"condition")}.',
f'What combined reputation belongs to {d(45)} whose reputation is at least {p(45,"condition")}?',
f'Find the least highly scored comment among {d(46)} and give its first 120 text characters and score.',
f'Please show {d(47)}, with the {field(47)} and score of each distinct post.',
f'I want the {field(48)} and score of the lowest-scoring post among {d(48)}.',
f'How many separate {d(49)} are recorded?',
f'What is the number of distinct {d(50)}?',
f'Create a score leaderboard of up to {p(51,"k")} {d(51)}, showing each {field(51)} and score.',
f'Find the maximum score among {d(52)}.',
f'What is the highest score of any of {d(53)}?',
f'Of {d(54)}, what is the greatest score?',
f'What total reputation do the different {d(55)} have?',
f'For each of {d(56)}, give the display name and number of distinct qualifying {associated(56)}.',
f'How much reputation does the most reputable of {d(57)} have?',
f'Calculate the total score of {d(58)} scoring at least {p(58,"condition")}, counting each post once.',
f'Show the display names of {d(59)} with at least {p(59,"threshold")} distinct qualifying {associated(59)}, along with those counts.',
f'What is the smallest score among {d(60)}?',
f'Which accepted answer has the weakest score among {d(61)}? Give its first 120 body characters and score.',
f'Choose the lowest-scoring question among {d(62)}. Show its {field(62)} and score.',
f'List unique comment previews for {d(63)} in alphabetical order, using the first 120 characters of text.',
f'What do the scores of all {d(64)} add up to?',
f'Give the {field(65)} and score for {d(65)}, with one entry per post.',
f'How low does the score go among {d(66)}?',
f'Which {p(67,"k")} {d(67)} have the highest scores? Show their {field(67)} and score.',
f'For {a68}, what is the total reputation associated with {b68} minus that associated with {c68}? Include each author once per named user.',
f'What is the least reputation recorded among {d(69)}?',
f'Total the scores across the distinct {d(70)}.',
f'Add together the reputation of the different {d(71)}.',
f'Which of {d(72)} has the largest stored usage count? Supply the tag name and count.',
f'Count {d(73)} whose score is at least {p(73,"condition")}, without counting a question twice.',
f'For the distinct {d(74)}, what is the average stored usage count?',
f'What stored usage count do {d(75)} average?',
f'Pick the highest-scoring comment among {d(76)}, showing its first 120 text characters and score.',
f'Give the {field(77)} and score for up to {p(77,"k")} highest-scoring {d(77)}.',
f'What is the average score across {d(78)}?',
f'Compute the mean score for {d(79)}.',
f'How many of {d(80)} have scores greater than or equal to {p(80,"condition")}?',
f'I am interested in the average score of {d(81)}.',
f'For each of {d(82)}, list the tag name and how many distinct qualifying {associated(82)} it appears on.',
f'Provide the distinct {field(83)} for {d(83)}, in alphabetical order.',
f'How many unique {d(84)} qualify?',
f'What is the minimum score found among {d(85)}?',
f'I need an alphabetical list of the distinct {field(86)} for {d(86)}.',
f'Find the largest score among {d(87)}.',
f'What is the sum of stored usage counts for the different {d(88)}?',
f'How many distinct posts are in {d(89)}?',
f'What total score is held by {d(90)}, once per distinct post?',
f'List the names of {d(91)} alphabetically, removing repeated names.',
f'Give the combined reputation of the distinct {d(92)}.',
f'What average reputation characterizes {d(93)}?',
f'What is the combined score of the different {d(94)}?',
f'How high is the maximum reputation among {d(95)}?',
f'Find the sum of scores for {d(96)}.',
f'What average score do the distinct {d(97)} receive?',
f'Calculate the mean score of {d(98)}, once per linked post.',
f'Identify the lowest-scoring post among {d(99)} and show its {field(99)} and score.'
]
if __name__=='__main__':append_batch(0,q)
