"""Fifth independently phrased question batch."""
from .question_authoring import d,m,p,field,associated,comparison,append_batch
r415,x415,y415=comparison(415);r435,x435,y435=comparison(435);r473,x473,y473=comparison(473)
q=[
f'How high is the greatest comment score for {d(400)}?',
f'What do the scores of the different {d(401)} add up to?',
f'For {d(402)}, find a reputation total that includes each author once.',
f'How much reputation is held by {d(403)} altogether?',
f'Calculate the score total of {d(404)} while ignoring any score below {p(404,"condition")}.',
f'Average reputation across the distinct {d(405)}.',
f'For the tag {p(406,"name")!r}, what different wiki post titles are recorded? Use the first 120 body characters for untitled posts and alphabetize the list.',
f'What unique post titles has user {p(407,"anchor")} written? Alphabetize them, substituting the first 120 body characters when a title is missing.',
f'Pick the question at the top of {d(408)} by score. Show its {field(408)} and score.',
f'I need a leaderboard of the {p(409,"k")} most-used {d(409)}, using stored counts and showing tag names with counts.',
f'List the distinct posts in {d(410)} with each {field(410)} and score.',
f'How many points does the best post in {d(411)} have?',
f'For {d(412)}, show a preview of the first 120 comment text characters and count distinct qualifying {associated(412)} for each comment.',
f'Within {d(413)}, add only scores reaching {p(413,"condition")} or more, using each answer once.',
f'Show the third-ranked question by score in {d(414)}, including its {field(414)} and score.',
f'What is the reputation total for {r415} associated with {x415} minus the one associated with {y415}? Use distinct qualifying users within each total.',
f'For {d(416)}, find the mean post score.',
f'How much reputation do the different {d(417)} have on average?',
f'Which post scores best out of {d(418)}? Show its {field(418)} together with the score.',
f'Give me a unique alphabetical list of previews for {d(419)}, taking the first 120 characters of each answer body.',
f'Count distinct posts that satisfy {d(420)}.',
f'Among {d(421)}, how many score no less than {p(421,"condition")}?',
f'Find a mean for the scores of the distinct {d(422)}.',
f'How many score points come from {d(423)} when scores below {p(423,"condition")} are left out?',
f'For the different {d(424)}, list each {field(424)} and score.',
f'What aggregate score comes from the distinct {d(425)}?',
f'Pick the post with the lowest score from {d(426)}; include its {field(426)} and score.',
f'Show each of {d(427)} with its first 120 body characters and score.',
f'Find the leading user by reputation in {d(428)} and show their display name and reputation.',
f'For {d(429)}, list up to {p(429,"k")} users with the greatest reputation, including display names and reputation.',
f'What score total is contributed by {d(430)} scoring at least {p(430,"condition")}?',
f'Find {d(431)} associated with at least {p(431,"threshold")} distinct qualifying {associated(431)} and give each {field(431)} and count.',
f'Give the {field(432)} and score for the strongest post by score in {d(432)}.',
f'For {d(433)}, show display names and associated counts where at least {p(433,"threshold")} distinct qualifying {associated(433)} occur.',
f'Who leads {d(434)} by reputation? List up to {p(434,"k")} display names with reputation.',
f'What is the difference between reputation totals for {r435} associated with {x435} and {y435}, first minus second? Count authors once per named user.',
f'Calculate a total from the scores of {d(436)}.',
f'What is the average of reputation among {d(437)}?',
f'Count the unique questions matching {d(438)}.',
f'Which {p(439,"k")} {d(439)} have the greatest reputation? Give display names and reputation in descending order.',
f'Average the scores for the distinct posts in {d(440)}.',
f'What percent of {d(441)} have positive scores? Count distinct posts and retain missing-score posts in the denominator.',
f'Find the largest answer score within {d(442)}.',
f'Give a mean score for the distinct posts in {d(443)}.',
f'Count the different posts meeting {d(444)}.',
f'How many distinct linked posts in {d(445)} meet or exceed a score of {p(445,"condition")}?',
f'How many posts by {p(446,"name")!r} score at least {p(446,"condition")}?',
f'Give up to {p(447,"k")} highest-reputation {d(447)} as display names with reputation.',
f'Find the top-scoring post from {d(448)}. Include its {field(448)} and score.',
f'What is the sum of scores no lower than {p(449,"condition")} among {d(449)}?',
f'Calculate a reputation total over {d(450)}, giving no contribution to reputation below {p(450,"condition")}.',
f'For {d(451)}, which comment has the smallest score? Show its first 120 text characters and score.',
f'Give the {field(452)} and score for every distinct post among {d(452)}.',
f'From {d(453)}, show the post with the least score, its {field(453)}, and the score.',
f'What number of posts do you find in {d(454)}, counting each just once?',
f'How many distinct linked posts are in {d(455)}?',
f'I want the best {p(456,"k")} {d(456)} on score, with each {field(456)} and score.',
f'For the questions in {d(457)}, what is their maximum score?',
f'What is the greatest number of score points earned by a post in {d(458)}?',
f'How high is the maximum score for posts in {d(459)}?',
f'Add up reputation over the different {d(460)}.',
f'Show the display name for each of {d(461)} and count its distinct qualifying {associated(461)}.',
f'How high does reputation go among {d(462)}?',
f'What score sum remains for {d(463)} after excluding scores below {p(463,"condition")}?',
f'Show display names and counts for {d(464)} associated with at least {p(464,"threshold")} distinct qualifying {associated(464)}.',
f'How many points does the lowest-scoring answer in {d(465)} have?',
f'Find the least highly scored answer among {d(466)}. Show the first 120 characters of its body and its score.',
f'What is the {field(467)} and score of the question ranked last by score in {d(467)}?',
f'For user {p(468,"anchor")}, list unique previews of their comments using the first 120 text characters, in alphabetical order.',
f'What combined score do {d(469)} have?',
f'For {d(470)}, give a post list with the {field(470)} and score, showing posts just once.',
f'What is the minimum score of a post authored by user {p(471,"anchor")}?',
f'Who has the best-scoring posts? For {d(472)}, list up to {p(472,"k")} posts with the highest scores, giving their {field(472)} and score.',
f'For {r473}, how much larger is the reputation total associated with {x473} than with {y473}? Return the signed first-minus-second difference, counting authors once per named user.',
f'What reputation does the lowest-reputation author among {d(474)} hold?',
f'What score total do posts in {d(475)} have, after counting each post once?',
f'What combined reputation comes from the distinct {d(476)}?',
f'For {d(477)}, show the tag with the highest stored usage count, including the name and count.',
f'Count distinct questions in {d(478)} with scores not below {p(478,"condition")}.',
f'What is mean stored usage count among the distinct {d(479)}?',
f'How high is stored usage count on average for {d(480)}?',
f'Give the first 120 text characters and score for the highest-scoring comment in {d(481)}.',
f'For {d(482)}, select the best {p(482,"k")} questions by score and show their {field(482)} and scores.',
f'Average the scores across all {d(483)}.',
f'How high is mean score for {d(484)}?',
f'How many questions are there in {d(485)} scoring at least {p(485,"condition")}?',
f'How many score points do comments in {d(486)} average?',
f'List tag names for {d(487)} and count the distinct qualifying {associated(487)} on which each appears.',
f'Alphabetically list the distinct {field(488)} for {d(488)}.',
f'What count of different questions matches {d(489)}?',
f'What is the least post score in {d(490)}?',
f'For {d(491)}, give the unique {field(491)} as an alphabetical list.',
f'Among {d(492)}, find the highest post score.',
f'What do the stored usage counts of the distinct {d(493)} add up to?',
f'How many separate posts has user {p(494,"anchor")} authored?',
f'Total scores for the different posts in {d(495)}.',
f'What tag names match {d(496)}? List unique names alphabetically.',
f'Add reputation from each distinct user in {d(497)}.',
f'How much reputation is held on average by {d(498)}?',
f'What score total belongs to the distinct {d(499)}?'
]
if __name__=='__main__':append_batch(400,q)
