"""Sixth batch, composed one instance at a time."""
from .question_authoring import d,m,p,field,associated,comparison,append_batch
r509,x509,y509=comparison(509);r550,x550,y550=comparison(550);r570,x570,y570=comparison(570)
q=[
f'What is the highest reputation held by {d(500)}?',
f'Add the scores for {d(501)}; what total is produced?',
f'For {d(502)}, how many score points do they average?',
f'Find a mean score for {d(503)}, with linked posts counted once.',
f'Which of {d(504)} comes last on score? Show its {field(504)} and score.',
f'What score is achieved on average by {d(505)}?',
f'Show the {field(506)} of {d(506)} with at least {p(506,"threshold")} distinct qualifying {associated(506)}, including the counts.',
f'How high is the mean post score for {d(507)}?',
f'How many comments by {p(508,"name")!r} have scores of {p(508,"condition")} or more?',
f'For {r509}, deduct the combined score associated with {y509} from that associated with {x509}. Include each distinct post once per named user.',
f'Calculate the average of the scores on {d(510)}, counting each post once.',
f'For posts by {p(511,"name")!r}, show each {field(511)} and score.',
f'Which accepted answer has the best score for questions titled {p(512,"title")!r}? Give its first 120 body characters and score.',
f'What reputation is held on average by the different {d(513)}?',
f'How high is average reputation among the distinct authors in {d(514)}?',
f'Count comments within {d(515)}, using distinct comments rather than repeated occurrences.',
f'Which comment by {p(516,"name")!r} scores highest? Show its first 120 text characters and score.',
f'Add up scores for the distinct posts voted on by {p(517,"name")!r}.',
f'What share of the distinct {d(518)} have positive scores, expressed as a percentage? Keep posts lacking scores in the total population.',
f'For {d(519)}, how much reputation do they have on average?',
f'How many points does the top-scoring post in {d(520)} earn?',
f'Total the scores of comments by user {p(521,"anchor")}.',
f'What is the minimum comment score recorded for {p(522,"name")!r}?',
f'Express the positive-score share of {d(523)} as a percentage. Count distinct posts and include missing-score posts in the denominator.',
f'How much reputation do {d(524)} have on average?',
f'What is the lowest score of a post that {p(525,"name")!r} voted on?',
f'How many different tag names match {d(526)}?',
f'Rank {d(527)} by descending stored usage count. Give the third tag’s name and count.',
f'Which post by user {p(528,"anchor")} has the greatest score? Show its {field(528)} and score.',
f'Within {d(529)}, how many users reach reputation of {p(529,"condition")} or above?',
f'How low is the smallest question score in {d(530)}?',
f'For tag {p(531,"name")!r}, identify the lowest-scoring wiki post by its {field(531)} and include its score.',
f'What is the least author reputation within {d(532)}?',
f'Show the {field(533)} and score of the lowest-scoring post voted on by {p(533,"name")!r}.',
f'For posts with revision activity by {p(534,"name")!r}, which scores highest? Give its {field(534)} and score.',
f'What is the maximum score of comments written by users who joined on {p(535,"date")}?',
f'Total the scores on distinct {d(536)}.',
f'What does reputation add up to across the distinct {d(537)}?',
f'What reputation total belongs to users in {d(538)}?',
f'From {d(539)}, sum scores of at least {p(539,"condition")} and give the total.',
f'What reputation do the authors in {d(540)} average?',
f'List the unique {field(541)} of wiki posts for {p(541,"name")!r} in alphabetical order.',
f'Give a unique alphabetical listing of the {field(542)} for posts by user {p(542,"anchor")}.',
f'Find the question scoring highest among {d(543)}. Show its {field(543)} and score.',
f'What are the top {p(544,"k")} {d(544)} on stored usage count? Include their names and counts.',
f'Show {d(545)} as a list of distinct posts with the {field(545)} and score.',
f'What maximum score occurs among the posts in {d(546)}?',
f'List comment previews from {d(547)}, taking the first 120 text characters, alongside counts of distinct qualifying {associated(547)}.',
f'Exclude scores below {p(548,"condition")} and total scores for the distinct {d(548)}.',
f'For {d(549)}, what is the fifth highest-scoring question? Give its {field(549)} and score.',
f'Find the reputation sum for {r550} associated with {x550} less the sum associated with {y550}, counting qualifying users once in each named user’s total.',
f'What mean score is recorded for the posts with revision activity by {p(551,"name")!r}?',
f'How much reputation do the distinct authors in {d(552)} hold on average?',
f'Which of {d(553)} is the top-scoring post? Supply its {field(553)} and score.',
f'Alphabetize the different answer previews for {d(554)}. Each preview should be the first 120 body characters.',
f'Count the distinct posts with revision activity by {p(555,"name")!r} that have at least one comment.',
f'What count of posts within {d(556)} have at least {p(556,"condition")} points?',
f'What is the average of post scores in {d(557)}?',
f'Total comment scores of {p(558,"condition")} or above for {p(558,"name")!r}.',
f'List the different posts with revision activity by {p(559,"name")!r}, showing their {field(559)} and score.',
f'Give a total of all scores for {d(560)}, once per distinct answer.',
f'Identify the post scoring least among {d(561)} by its {field(561)} and provide its score.',
f'For questions titled {p(562,"title")!r}, list their accepted answers with the first 120 body characters and score.',
f'Name the highest-reputation author within {d(563)} using their display name, and give their reputation.',
f'Who are the best {p(564,"k")} users by reputation in {d(564)}? Show their display names and reputation.',
f'For posts by {p(565,"name")!r}, sum scores at or above {p(565,"condition")}.',
f'List {d(566)} associated with at least {p(566,"threshold")} distinct qualifying {associated(566)}, using their {field(566)} and the associated counts.',
f'What is the {field(567)} and score of the highest-scoring post authored by holders of the {p(567,"badge")!r} badge?',
f'Which authors in {d(568)} are associated with at least {p(568,"threshold")} distinct qualifying {associated(568)}? Give display names and counts.',
f'List the best {p(569,"k")} {d(569)} by reputation, paired with their display names and reputation.',
f'Calculate reputation totals for {r570} associated with {x570} and with {y570}. Give the former minus the latter, using distinct authors for each named user.',
f'What is the combined score of posts by {p(571,"name")!r}?',
f'What mean reputation is recorded for {d(572)}?',
f'Count the distinct questions among posts commented on by holders of the {p(573,"badge")!r} badge.',
f'Give the top {p(574,"k")} {d(574)} on reputation, showing display names and reputation.',
f'Average scores for posts voted on by user {p(575,"anchor")} that have a recorded title.',
f'What percentage of distinct posts by holders of the {p(576,"badge")!r} badge have positive scores? Include posts with missing scores in the denominator.',
f'For accepted answers to questions created on {p(577,"date")}, what is the largest score?',
f'Find the average score for {d(578)}, once per distinct post.',
f'What number of distinct posts meets {d(579)}?',
f'Among {d(580)}, how many different posts have at least {p(580,"condition")} points?',
f'For {p(581,"name")!r}, count authored posts scoring {p(581,"condition")} or above.',
f'Show the {p(582,"k")} most reputable {d(582)} as display names with reputation.',
f'Which post has the greatest score among those commented on by users who joined on {p(583,"date")}? Give its {field(583)} and score.',
f'Add only scores at or above {p(584,"condition")} within {d(584)}.',
f'For {d(585)}, what is the total reputation if contributions below {p(585,"condition")} are omitted?',
f'Show the lowest-scoring comment by {p(586,"name")!r}, using its first 120 text characters and score.',
f'What posts has {p(587,"name")!r} voted on? List each distinct {field(587)} and score.',
f'Which linked post in {d(588)} scores lowest? Give its {field(588)} and score.',
f'How many different posts has {p(589,"name")!r} voted on?',
f'Count the unique posts linked to from posts titled {p(590,"title")!r}.',
f'Which {p(591,"k")} {d(591)} score highest? Show each {field(591)} and score.',
f'How high is the maximum question score for {d(592)}?',
f'What is the maximum score among posts commented on by {p(593,"name")!r}?',
f'Find the greatest score of a post voted on by user {p(594,"anchor")}.',
f'How much reputation do authors of questions answered by user {p(595,"anchor")} have altogether? Count each author once.',
f'For {d(596)}, list display names and counts of distinct qualifying {associated(596)}.',
f'Find the greatest reputation within {d(597)}.',
f'What total score comes from distinct posts in {d(598)} scoring at least {p(598,"condition")}?',
f'List display names and associated counts for {d(599)} having at least {p(599,"threshold")} distinct qualifying {associated(599)}.'
]
if __name__=='__main__':append_batch(500,q)
