"""Individually written questions, frozen after rendered-text review."""
from .v4_batch2_question_authoring import append_batch

q=[
'What percentage of the questions to which answers with score between 3 and 8 inclusive respond score positively? Use all matching questions, including those without scores, as the denominator.',
"Give the positive-score percentage for posts titled 'Testing significance of a random effect glmmADMB model', counting all matching posts, even those with no score.",
'What fraction of the posts with score between 0 and 11 inclusive has a score above zero? Return a percentage based on every matching post, including unscored ones.',
'Among the questions created on 2014-04-26, find the percentage with scores greater than zero, keeping every matching question in the denominator.',
'How frequent are positive scores in the questions created on 2011-08-23? Give their percentage out of all matching questions, including those without scores.',
"For questions titled 'Kriging on log transformed rainfall data', calculate the percentage that score above zero; include unscored questions in the total.",
"What percentage of all questions titled 'Logistic input with Gaussian noise' have positive scores? Retain questions without a score in the denominator.",
"Give the percentage with scores greater than zero for questions titled 'Library for Bayesian infinite mixture models', using every matching question as the total.",
'What share of the questions to which answers created on 2012-08-02 respond scores positively? Return a percentage of all matching questions, including unscored ones.',
'For the questions to which answers created on 2014-04-07 respond, calculate the positive-score percentage with every matching question in the denominator, regardless of missing scores.',
"How frequently do scores exceed zero among the posts authored by the user 'user49653'? Give the percentage of all matching posts, including those without scores.",
"Return the percentage of the posts authored by the user 'William J. Denny' with positive scores, using all matching posts including unscored posts as the denominator.",
'What is the positive-score percentage of the posts with revision activity by users who joined on 2011-10-09 when all matching posts, even unscored ones, are counted in the total?',
'Among all the posts with revision activity by users who joined on 2011-02-01, calculate the percentage whose score exceeds zero; keep posts without scores in the denominator.',
'Within the questions with score between 1 and 9 inclusive, what percentage of the matching questions have positive scores? Include unscored questions in the total.',
"Show the score and title of the highest-scoring post in the posts linked to from posts titled 'How can you have a non-significant multiple regression model w/ significant predictors?', with the first 120 body characters used for an absent title.",
"Among the posts authored by holders of the 'outliers' badge, which post has the best score? Return its score and title or first-120-character body excerpt if untitled.",
"Return the score and identifying title of the top-scoring post among the posts authored by holders of the 'data-visualization' badge; use its first 120 body characters if untitled.",
"Find the highest-scoring post in the posts authored by holders of the 'Yearling' badge, showing the score alongside its title or first 120 body characters.",
'Which post in the posts commented on by users who joined on 2011-04-11 has the greatest score? Give that score and the title, substituting the first 120 body characters if missing.',
"What comment has the best score among the comments by authors of posts linked to from posts by the user 'benhamner'? Show the score and its first 120 text characters.",
"For the comments by authors of posts linked to from posts by the user 'orpetil', pick the highest-scoring comment and give its score with the opening 120 characters of its text.",
"Return the score and first-120-character text preview of the best-scoring comment among the comments by authors of posts linked to from posts by the user 'user678613'.",
"Which comment scores lowest in the comments written by the user 'user42628'? Give its score and first 120 text characters.",
"Give the lowest score and the corresponding post title in the posts linked to from posts titled 'Maximum of sample variance', substituting first-120-character body text for a missing title.",
"Find the lowest-scoring answer among the accepted answers to questions titled 'Will quantum computing allow new statistical techniques?', returning its score and its first 120 body characters.",
"Among the wiki posts for the tag 'nnt', identify the worst-scoring post and show its score with the title or first 120 body characters.",
"What post scores least in the posts voted on by the user 'M. Tibbits'? Return that score and its title, or first 120 body characters when untitled.",
"Compare the combined reputation of authors of posts linked to from posts with revision activity by each named user associated with 'Paul Belardi' and 'user44958'. Subtract the second total from the first, counting each author once per named user.",
"Calculate the reputation-total gap for authors of posts linked to from posts with revision activity by each named user between 'CCL' and 'user14490', first minus second. Count each author once for each named user.",
"How much is the combined reputation of authors of posts linked to from posts with revision activity by each named user for 'Endy Tjahjono', less the corresponding total for 'atwell17'? Count each author once per named user.",
"Take the total reputation of authors of posts linked to from posts with revision activity by each named user for 'user54294' and subtract the total for 'Piers Karsenbarg'; what result do you get, once per author per named user?",
"Using authors of posts linked to from posts by each named user, give the reputation total associated with 'Ahmad Vazehi' minus the one associated with 'user4045', without counting an author twice for either named user.",
'How many posts in the posts with score between 4 and 26 inclusive have scores at least 2?',
'What count of the posts with score between 4 and 7 inclusive reaches a score of 2 or more?',
'Count posts among the posts with score between 0 and 1 inclusive whose scores meet a minimum of 6.',
'For the posts with score between 1 and 2 inclusive, how many posts score 1 or higher?',
"How many of the posts linked to from posts titled 'How to normalize data to 0-1 range?' have a score greater than or equal to 8.0?",
"Count posts scoring at least 12.0 among the posts authored by the user 'ratsalad'.",
'What is the count of questions in the questions to which answers created on 2014-08-21 respond with scores of at least 5.0?',
'How many questions among the questions with score between 5 and 11 inclusive reach 3 points or more?',
"Give the count of comments scoring at least 0.0 within the comments written by the user 'user1146372'.",
"How many comments among the comments written by the user 'BST' meet a minimum score of 0.0?",
"What number of the comments written by the user 'CraigMilligan' score 1.0 or higher?",
'Total the scores of answers among the accepted answers to questions created on 2010-10-31 that reach at least 7.0 points.',
'What score sum comes from the accepted answers to questions created on 2013-06-07 when only answers scoring 1.0 or more contribute?',
"Add scores from the comments written by the user 'user11170' only when they are at least 0.0. What sum do you get?",
"For the comments written by the user 'Marcin Korn', calculate the total score of comments scoring no less than 0.0.",
"What combined score is contributed by the posts authored by the user 'William J. Denny' with scores at least 3.0?",
"Sum the scores of posts in the posts authored by the user 'VARNOLD' that score 2.0 or higher.",
"From the posts authored by the user 'ulidtko', add only scores reaching 0.0 or more; what is the total?",
"Find the total score of the posts linked to from posts titled 'Is it valid to include several interaction terms but exclude main effects because only interaction effects are significant?' that meet a minimum score of 37.0.",
'For the posts linked to from posts titled \'What aspects of the "Iris" data set make it so successful as an example/teaching/test data set\', how much do the scores sum to after excluding posts scoring below 24.0?',
'Calculate the score total for questions in the questions to which answers created on 2014-04-07 respond scoring at least 0.0.',
'Add the scores of the questions to which answers created on 2013-06-17 respond whose scores are 1.0 or higher.',
'How many distinct comments occur among the comments by authors of posts linked to from posts by the user with ID 7225?',
'Give a count of the different comments in the comments by authors of posts linked to from posts by the user with ID 7073.',
"Which of the authors of posts linked to from posts commented on by the user 'gina_l' authored at least 1 distinct qualifying post linked to from those commented-on posts? Show display names and those post counts, ordered by user ID.",
"List the display names and distinct qualifying-post counts for the authors of posts linked to from posts commented on by the user 'Eric Lippert' who authored at least 1 post linked to from those commented-on posts. Order by user ID.",
"What is the number of distinct posts in the posts with revision activity by the user 'metrobalderas' with at least one comment?",
"How many different posts satisfy the posts with revision activity by the user 'esengie' with at least one comment?",
"Count the distinct posts matching the posts with revision activity by the user 'tyranitar' with at least one comment.",
"What number of distinct questions is represented by the posts commented on by holders of the 't-test' badge that are questions?",
"What is the largest reputation recorded among the authors of posts linked to from posts with revision activity by the user 'jrc1000'?",
"Find the greatest reputation in the authors of posts linked to from posts with revision activity by the user 'Anastasios Ventouris'.",
"Among the authors of posts linked to from posts with revision activity by the user 'Jake Larson', how high is the maximum reputation?",
'What is the least reputation recorded for the authors of posts linked to from posts with revision activity by users who joined on 2012-03-06?',
'Find the smallest reputation among the authors of posts linked to from posts with revision activity by users who joined on 2013-02-06.',
'Among the authors of posts linked to from posts with revision activity by users who joined on 2013-02-26, give the minimum reputation.',
"Calculate the average score of the posts commented on by authors of posts linked to from posts titled 'Constrained and Weighted Regression' with a recorded title.",
"What is the mean score for the posts commented on by authors of posts linked to from posts titled 'Frequency of combinations possible' with a recorded title?",
'Rank the questions to which answers created on 2012-10-05 respond by descending score and select position 3. Give its score and title, using the first 120 body characters if untitled.',
'Which question ranks 3 by score among the questions to which answers created on 2013-08-27 respond? Show that score and its title or first 120 body characters when untitled.',
'Calculate the combined reputation of the distinct authors of posts linked to from posts commented on by the user with ID 37976.',
"Which 3 authors among the authors of posts linked to from posts commented on by the user 'tjnel' have the largest reputation? Give display names and reputation in descending order.",
"Return up to 3 of the authors of posts linked to from posts commented on by the user 'user2328833' ranked by highest reputation, including their display names and reputation.",
"Who ranks in the top 3 among the authors of posts linked to from posts commented on by the user 'user20061' by reputation? List display names and reputation, largest first.",
"Find the 10 most reputable users in the authors of posts linked to from posts commented on by the user 'tobip' and show their display names with reputation in descending order.",
"What average reputation do the authors of posts linked to from posts with revision activity by the user 'SpammerSlammer' have, restricting authors to users who joined in 2010?",
"For authors of posts linked to from posts with revision activity by the user 'kmm' who joined in 2012, how much reputation do they have on average?",
]
append_batch(200,q)
