"""Individually written questions, frozen after rendered-text review."""
from .v4_batch2_question_authoring import append_batch

q=[
'For the authored posts in the posts authored by users with reputation exactly 63, can you show titles (or the first 120 body characters for untitled posts), score and view counts?',
'What titles were used for the posts authored by users with reputation exactly 83? When untitled, show the first 120 body characters.',
'Pair each title of the posts authored by users with reputation exactly 2 with its score; an untitled post should use its first 120 body characters.',
'What title identifies the post with ID 1257? If absent, use the first 120 body characters.',
'Bring up the titles of the posts created on 2013-05-15, with the first 120 body characters replacing missing titles.',
'Which titles and scores are recorded for the posts created on 2013-12-17? Substitute first-120-character body excerpts for missing titles.',
"What date and time was the user account 'Alex V' created?",
"How much reputation does 'user2621147' have?",
"Give the tag names found in the tags on posts authored by the user 'user6143'.",
"I want to know which tags are present in the tags on posts authored by the user 'lsdr'. Show their names.",
"List the tags on posts authored by the user 'user25452' by name.",
'Can you retrieve titles (or the first 120 body characters for untitled posts), score and view counts for the posts commented on by users with reputation exactly 138?',
'Show the score alongside the title of each post in the posts commented on by users with reputation exactly 196, using its first 120 body characters when untitled.',
'Please bring back the titles (or the first 120 body characters for untitled posts) for the posts commented on by users with reputation exactly 4800.',
"Which authors are represented by the authors of posts linked to from posts titled 'Methods for analyzing pre/post test data'? Answer with display names.",
"For the users in the authors of posts linked to from posts titled 'What test is appropriate for binary outcome with repeated measures and binary, ordinal and continuous independent variables?', provide display names, reputation and locations.",
"Give the authors' display names for the authors of posts linked to from posts titled 'How to scale a variable to a specific mean and standard deviation'.",
"What names are shown for the authors of posts linked to from posts titled 'Non-normal data and non-parametric tests'?",
'Identify the people among the authors of accepted answers to the question with ID 13303 by display name.',
'Return the saved names of the authors of accepted answers to the question with ID 104333.',
"I would like the titles of the posts authored by the user 'user53594', with a first-120-character body excerpt for every untitled post.",
"Look up the titles and scores for the posts authored by the user 'user25971'. Replace missing titles with the first 120 body characters.",
"Present the posts authored by the user 'Misscats' by title, or by the first 120 body characters if no title is stored.",
'What post text identifies the posts with revision activity by the user with ID 36522? Show the title, falling back to the first 120 body characters.',
'Retrieve titles for the posts with revision activity by the user with ID 12738; use a 120-character body excerpt for an untitled post.',
'I need a title-and-score list for the posts authored by the user with ID 13984 who have badges, with the first 120 body characters used instead of any missing title.',
'Which tags belong to the tags on posts authored by users with reputation exactly 75? Give their names.',
'Show the tag names and stored usage counts for the tags on posts authored by users with reputation exactly 39.',
"Provide the titles (or the first 120 body characters for untitled posts) found among the posts commented on by the user 'Anton K'.",
'What titles are available for the posts commented on by users who joined on 2014-03-31? Use the first 120 body characters in place of absent titles.',
'List the titles identifying the posts with revision activity by users with reputation exactly 822, replacing each missing title with the first 120 body characters.',
'For the posts with revision activity by users with reputation exactly 429, show scores with titles or first-120-character body excerpts.',
"How often is the tag 'covariate' used according to its stored usage count? Include its tag name.",
'Which display names identify the authors of accepted answers to questions created on 2011-09-23?',
'Retrieve display names, reputation and locations for the authors of accepted answers to questions created on 2014-05-02.',
'What names were recorded for the users who joined on 2014-03-01?',
'Give me the saved display names belonging to the users who joined on 2010-08-28.',
'Look up the titles (or the first 120 body characters for untitled posts) identifying the posts voted on by users who joined on 2010-07-20.',
'What are the tag names associated with the tags on posts authored by the user with ID 27515?',
'Bring back the titles (or the first 120 body characters for untitled posts) for the posts linked to from posts created on 2013-06-04.',
'Can I see the first 120 text characters of the comments written by the user with ID 27497?',
'Show how the comments written by the user with ID 4173 begin, using a 120-character text preview for each.',
"For the comments written by the user with ID 40879, return the score with the first 120 characters of each comment's text.",
'Who is the user with ID 36379? Give the display name.',
'What saved name identifies the user with ID 43661?',
'Which titles and scores belong to the posts voted on by users with reputation exactly 146? For untitled posts, use their first 120 body characters.',
"Retrieve a preview of the comments written by users who joined on 2013-04-05, taking each comment's first 120 text characters.",
'Give the question titles associated with the questions to which answers created on 2012-08-22 respond, using the first 120 body characters when untitled.',
'What question text identifies the questions to which answers created on 2014-09-04 respond? Show titles or the first 120 body characters for untitled questions.',
'List the display names belonging to the authors of posts linked to from posts created on 2014-08-08.',
'What questions appeared then? Give the question titles (or the first 120 body characters when untitled) for the questions created on 2010-08-25.',
'For the questions created on 2014-04-01, retrieve titles or first-120-character body excerpts for missing titles.',
'Give the score and view count of each of the questions created on 2010-11-29, alongside its title or first 120 body characters.',
'Which question titles (or the first 120 body characters when untitled) are available for the questions created on 2013-11-04?',
'Name the tags within the tags with stored usage count exactly 9.',
'I only want the names of the tags with stored usage count exactly 131.',
'Give the title belonging to the question with ID 104572, substituting its first 120 body characters if untitled.',
'What is the question with ID 44737 called? Return its title or first 120 body characters when untitled.',
"Who authored the accepted answers? For the authors of accepted answers to questions titled '(Prediction) constrained OLS in R', give display names, reputation and locations.",
'Let me see 120-character text excerpts from the comments written by users with reputation exactly 149.',
"What creation date and time are recorded for questions titled 'If my normality test is non-significant, am I safe to use the t-test?'?",
'Find titles and scores for the posts commented on by the user with ID 43386, using the first 120 body characters where a title is missing.',
'Give a title list for the posts authored by users who joined on 2014-03-28 who have badges. Untitled posts should use their first 120 body characters.',
'Which post titles are recorded in the posts linked to from the post with ID 115264? Substitute the first 120 body characters for missing titles.',
'What text names the posts linked to from the post with ID 31989? Return titles or first-120-character body excerpts when untitled.',
'Collect the titles of the posts linked to from the post with ID 105542, with the first 120 body characters used as a fallback.',
'For the posts linked to from the post with ID 95567, identify posts using their titles or, when untitled, the first 120 body characters.',
"Quote the first 120 characters from the text of the comments written by the user 'Anthony Damico'.",
"Look up the scores of posts titled 'Statistical method to compare time-series with different periods'.",
"For posts titled 'Concavity of log likelihood for hidden markov models', show the stored view counts.",
"On what dates and times were posts titled 'Plotting the coverage of the confidence interval as a function of sample size using Monte Carlo in R' created?",
'Which title or first-120-character body excerpt identifies each of the posts authored by the user with ID 22175?',
'Return titles, scores and view counts for the posts authored by the user with ID 4108, substituting the first 120 body characters for missing titles.',
"What titles or first-120-character body excerpts are shown for the posts with revision activity by the user 'Paul Belardi'?",
"For the posts with revision activity by the user 'Pelotas', give a list of titles, using the first 120 body characters whenever a title is missing.",
"Bring back titles, scores and view counts of the posts with revision activity by the user 'mikebmassey'. An untitled post should use its first 120 body characters.",
"How are the posts with revision activity by the user 'user34773' titled? Replace absent titles with 120-character body excerpts.",
'Which names identify the tags in the tags on posts authored by users who joined on 2012-11-19?',
'Show the score and view count beside each title in the posts with revision activity by users who joined on 2014-06-13; use the first 120 body characters if untitled.',
'I need to identify the posts voted on by the user with ID 3026 by title or by the first 120 body characters when untitled.',
'Look up titles for the posts voted on by the user with ID 2633, replacing untitled entries with their first 120 body characters.',
'What titles were recorded for the posts voted on by the user with ID 1723? Use the first 120 body characters in place of missing titles.',
'Find the display names of the authors among the authors of posts linked to from the post with ID 73208.',
'For the authors of posts linked to from the post with ID 101560, bring back display names with reputation and location.',
'Produce a list of different titles for the posts linked to from the post with ID 110272, using the first 120 body characters for untitled posts and removing repeated text.',
'Which unique titles identify the questions created on 2013-11-04? Use the first 120 body characters for a missing title.',
"Retrieve the distinct titles of the posts authored by the user 'petroica', with the first 120 body characters substituted when untitled.",
"What different title text appears in the posts authored by the user 'Leotardo'? Untitled posts should use their first 120 body characters.",
'List the different previews of the accepted answers to the question with ID 86474, taking the first 120 characters of the body.',
'What distinct opening text is found in the accepted answers to the question with ID 18363? Return first-120-character body previews.',
'For the accepted answers to questions created on 2014-07-28, collect the first 120 body characters of each answer and remove duplicate previews.',
'Show each unique first-120-character body preview among the accepted answers to questions created on 2012-10-23.',
'What different comment beginnings occur in the comments written by the user with ID 27497? Use the first 120 characters of the text.',
'Return a deduplicated list of first-120-character text previews for the comments written by the user with ID 53068.',
'Give the unique title text from the posts created on 2013-04-13, with a 120-character body excerpt used when no title is recorded.',
'Collect distinct titles for the posts created on 2013-12-17; missing titles should be replaced with the first 120 body characters.',
'Which distinct question titles correspond to the questions to which answers created on 2014-04-24 respond? Fall back to first-120-character body excerpts for missing titles.',
"Find different titles among the posts authored by users who joined on 2014-07-18, using each untitled post's first 120 body characters.",
'For the questions to which the answer with ID 111660 responds, show each different title or first-120-character body excerpt once.',
'Give a distinct list of title text for the questions to which the answer with ID 70980 responds, taking the first 120 body characters instead where titles are absent.',
]
append_batch(0,q)
