"""Individually written questions, frozen after rendered-text review."""
from .v4_batch2_question_authoring import append_batch

q=[
"Which different titles occur in the posts authored by the user with ID 29567? Use each untitled post's first 120 body characters.",
'Give the distinct titles from the posts authored by the user with ID 34828, substituting the first 120 body characters where titles are missing.',
'For the posts authored by the user with ID 53594, return each unique title or first-120-character body excerpt once.',
"Find the distinct stored usage count for the tag 'sphericity'.",
'What distinct post text represents the posts linked to from posts created on 2014-05-07? Use titles or the first 120 body characters when untitled.',
'Collect the different first-120-character text previews of the comments written by users who joined on 2012-04-26.',
'Which unique comment previews can be read in the comments written by users who joined on 2013-11-12? Take the first 120 text characters of each.',
"Give a deduplicated list of titles for the posts with revision activity by the user 'Gabriel Wajnberg', with the first 120 body characters replacing missing titles.",
"What distinct view counts do posts titled 'One-Way ANOVA experiment ideas' have?",
'How many posts meet the conditions in the posts with score between 1 and 12 inclusive?',
'What is the size of the set of the posts with score between 2 and 4 inclusive?',
'Count the accepted answers in the accepted answers to questions with score between 2 and 10 inclusive.',
'How many authored posts can you find for the posts linked to from the post with ID 14045?',
'What is the total count of the posts linked to from the post with ID 26293?',
'Give the number of accounts among the users who joined on 2010-08-28.',
'How many users joined as described by the users who joined on 2012-05-02?',
'What post total is found for the posts created on 2011-12-01?',
'How many posts were created under the conditions of the posts created on 2011-10-11?',
'Return the number of posts in the posts created on 2013-12-17.',
'Count how many answers are included in the accepted answers to questions created on 2014-07-28.',
'How many questions satisfy the questions with score between 0 and 11 inclusive?',
'What question total matches the questions with score exactly 5?',
'Give the number of questions belonging to the questions with score exactly 1.',
'How many posts are referenced in the posts linked to from posts created on 2011-03-17?',
'Count the referenced posts among the posts linked to from posts created on 2012-07-27.',
'What is the number of comments written in the comments written by users who joined on 2013-02-20?',
'How many comments were authored as described by the comments written by users who joined on 2013-11-12?',
'Give the total comment count for the comments written by users who joined on 2013-02-12.',
'What number of posts is attributed to the author in the posts authored by the user with ID 29894?',
'Count the authored posts matching the posts authored by the user with ID 34828.',
'How many comments does the comments written by the user with ID 36999 contain?',
"Count all posts that appear as the posts linked to from posts titled 'Relevance of opinion poll (500 people from 10.5 millions)'.",
'What number of authored posts meets the posts authored by users with reputation between 83 and 148 inclusive?',
'How many posts belong to the users described in the posts authored by users with reputation between 8 and 25 inclusive?',
'Count the users satisfying the users with reputation between 10 and 11 inclusive.',
'What total number of users falls within the users with reputation exactly 101?',
'Give the count of accounts matching the users with reputation between 1 and 4 inclusive.',
"How many posts belong to the author in the posts authored by the user 'Ryu'?",
"What is the authored-post count for the posts authored by the user 'user53594'?",
"Count all authored posts represented by the posts authored by the user 'KevinL'.",
'What comment count is associated with the comments written by users with reputation between 14 and 143 inclusive?',
"How many comments can you find for the comments written by the user 'GollyJer'?",
'How many of the posts authored by the user with ID 13724 have titles? Return only the count.',
'For users who joined on 2014-06-23 and have authored posts, return the number written by each user, without names.',
'Show display names, reputation and authored-post counts for the authors among users who joined on 2012-07-10 who have at least one post.',
'For the authors among users who joined on 2012-11-14 with untitled posts, how many such posts did each author write? Show only the counts.',
'What is the untitled-post total for the user with ID 12924? Give only the count.',
"Count every post authored by the user 'user53594' and return that total alone.",
"How many authored posts are recorded for the user 'Misscats'? Do not include names in the answer.",
'Among users who joined on 2012-03-15 who authored titled posts, give the number of such posts per user, without names.',
'For the authors among users who joined on 2012-01-24 with titled posts, show display names and the counts of posts with a recorded title.',
"What number of titled posts was authored by the user 'Alexander Chervov'?",
"Return just the count of authored posts with a recorded title for the user 'Skumin'.",
"What untitled-post count is recorded for the user 'Ufuk Can Biçici'?",
"Count the posts without recorded titles written by the user 'Fredrik Bonander'. Return the count alone.",
"For the user 'Johann Hibschman', how many posts did they author without a recorded title? Show only the count.",
"How many comments did the user 'Andrei Kucharavy' write? Give only the count.",
"What is the number of comments authored by the user 'George Dontas'?",
"Show the display name and comment count of the user 'Matt Duffin'.",
"Count the comments written by the user 'vc15', returning the count alone.",
'Among users who joined on 2010-07-19 who have written comments, how many did each write? Return only per-user counts.',
"For users who joined on 2011-07-29 and wrote at least one comment, give each author's total comment count without names.",
'Count comments separately for the authors among users who joined on 2013-04-24, excluding users with no comments; return counts only.',
'What number of comments did the user with ID 48564 write?',
'Give the total comment count for the user with ID 20856.',
'Count every comment authored by the user with ID 46019 and show only the count.',
'For the user with ID 7789, what is the authored-comment total?',
'Return the number of comments attributed to the user with ID 30540.',
'Among the questions to which answers created on 2014-01-26 respond, which question has the greatest score? Give its title or first 120 body characters if untitled.',
'What title identifies the best-scoring question in the questions to which answers created on 2014-04-27 respond? For a missing title, use the first 120 body characters.',
"Return the title of the top-scoring post in the posts linked to from posts titled 'A naive question about the Kolmogorov Smirnov test', with its first 120 body characters used if untitled.",
"Which comment in the comments written by the user 'May Pi' has the smallest score? Show its first 120 text characters.",
"Give a first-120-character text preview of the lowest-scoring comment among the comments written by the user 'BI Guy'.",
"Find the comment scoring least in the comments written by the user 'Caluchko' and return its opening 120 text characters.",
"What title identifies the lowest-scoring post in the posts linked to from posts titled 'Any algorithms better than polynomial regression'? Use its first 120 body characters if absent.",
"Which post in the posts linked to from posts titled 'How to find a good fit for semi-sinusoidal model in R?' scores worst? Give its title or first 120 body characters.",
"Show the title of the least-scored post among the posts linked to from posts titled 'K-fold or hold-out cross validation for ridge regression using R', substituting its first 120 body characters when untitled.",
"Find the post with the smallest score among the posts linked to from posts titled 'When will PCA be equivalent to ICA?'; return its title or first-120-character body excerpt.",
"What are the first 120 body characters of the lowest-scoring answer among the accepted answers to questions titled 'Entropy (individuals equally high on all items vs. high on only few items)'?",
"Identify the answer scoring least in the accepted answers to questions titled 'Statistical Model from distributions' using its first 120 body characters.",
'Which question among the questions to which answers created on 2013-05-13 respond has the smallest score? Give its title or first 120 body characters.',
'For the posts commented on by the user with ID 48811, return the title and score of the worst-scoring post, replacing an absent title with its first 120 body characters.',
'Find the post with the least score in the posts commented on by the user with ID 26000 and show that score with its title or first 120 body characters.',
"Return a first-120-character body preview of the best-scoring answer in the accepted answers to questions titled 'Using Mutual Information for Binary Logistic Regression Variable Selection'.",
"Which answer among the accepted answers to questions titled 'One-class Classification of multidimensional vectors' has the greatest score? Show its opening 120 body characters.",
"Find the highest-scoring comment among the comments written by the user 'Bird Jaguar IV'; give its first 120 text characters.",
"What opening text identifies the best-scoring comment in the comments written by the user 'tfunk'? Return its first 120 characters.",
'Which title identifies the highest-scoring post in the posts authored by the user with ID 9858? Use its first 120 body characters if no title is recorded.',
'Find the greatest-scoring post in the posts authored by the user with ID 7754 and show its title or first-120-character body excerpt.',
"What is the title of the post with the lowest score among the wiki posts for the tag 'stan'? Replace a missing title with its first 120 body characters.",
"Give the title or first 120 body characters of the worst-scoring post among the wiki posts for the tag 'model'.",
"Identify the smallest-scoring post in the wiki posts for the tag 'two-step-estimation' by title, using its first 120 body characters if untitled.",
"For the posts voted on by the user 'Jakob Borg', show the lowest-scoring post's score and title or first 120 body characters.",
"Which of the posts with revision activity by the user 'Khader Shameer' has the greatest score? Return its score beside its title, or first 120 body characters when untitled.",
'What percentage of all the posts linked to from the post with ID 85644 have scores greater than zero? Include posts with no score in the denominator.',
'Calculate the proportion of the posts linked to from posts with score between 0 and 11 inclusive with positive scores as a percentage of all matching posts, including unscored ones.',
'Of all the accepted answers to questions with score between 2 and 122 inclusive, what percentage have scores above zero? Include answers without scores in the total.',
'Considering the question with ID 103974, give the percentage of matching questions whose score is positive; all matching questions, even unscored ones, count in the denominator.',
'For the posts created on 2013-06-14, what is the percentage scoring above zero, using every matching post including unscored posts as the total?',
'How large is the positive-score share of the posts created on 2011-07-10? Express it as a percentage of all matching posts, including those without scores.',
]
append_batch(100,q)
