"""Individually written questions, frozen after rendered-text review."""
from .v4_question_authoring import append_batch

q=[
'What are the titles (or the first 120 body characters for untitled posts) of the posts authored by users with reputation exactly 180?',
'List the posts authored by users with reputation exactly 104, showing their titles (or the first 120 body characters for untitled posts).',
'Find the post with ID 44437 and give its title or, if untitled, its first 120 body characters.',
'I need the title of the post with ID 18786; use its first 120 body characters if it is untitled.',
'How is the post with ID 41004 titled? Show its first 120 body characters if the title is missing.',
'Show the title of the post with ID 109288, or its first 120 body characters if untitled.',
'Which titles (or the first 120 body characters for untitled posts) belong to the posts created on 2012-05-10?',
'Give the titles of the posts created on 2013-03-18; substitute the first 120 body characters when a title is absent.',
"How much reputation is recorded for 'ShikharDua'?",
"What reputation does the user 'Sirenology' have?",
"When was the user account 'Lyen Huang' created? Give the date and time.",
"For the tags on posts authored by the user 'Guest483', provide the tag names with their stored usage counts.",
'Which post titles appear among the posts commented on by users with reputation exactly 71? For untitled posts, show the first 120 body characters.',
"Who are the authors of posts linked to from posts titled 'Dickey-Fuller augmented tests: how to choose lags?'? I only need display names.",
"What titles were given to the posts authored by the user 'petroica'? For untitled posts, show the first 120 body characters.",
"Show me the posts authored by the user 'user43222' by title, using the first 120 body characters when no title is recorded.",
'For the posts with revision activity by the user with ID 22549, list titles (or the first 120 body characters for untitled posts), score and view counts.',
'Which tag names occur on posts authored by users with reputation exactly 158?',
"Give titles (or the first 120 body characters for untitled posts), score and view counts for the posts commented on by the user 'martinthenext'.",
'Name the posts among the posts commented on by users who joined on 2013-07-09, with the first 120 body characters replacing missing titles.',
'I want titles (or the first 120 body characters for untitled posts), score and view counts for each of the posts with revision activity by users with reputation exactly 42.',
"Look up the stored usage count of the tag 'moments'.",
"How often is the tag 'sphericity' used according to its stored usage count?",
"What stored usage count does the tag 'hotelling' have?",
"Give the recorded usage count for the tag 'multiple-comparisons'.",
'Give the display names and reputation of the users who joined on 2013-12-18.',
'Who joined then? List the display names of the users who joined on 2012-03-21.',
'Please identify the users who joined on 2012-04-16 by display name.',
'What are the names of the tags on posts authored by the user with ID 10117?',
'For the posts linked to from posts created on 2014-07-01, I only need titles or the first 120 body characters when untitled.',
'Describe the posts linked to from posts created on 2014-05-13 with titles (or the first 120 body characters for untitled posts), score and view counts.',
'What titles do the posts linked to from posts created on 2013-11-06 have? Replace missing titles with the first 120 body characters.',
'List the titles (or the first 120 body characters for untitled posts) found for the posts linked to from posts created on 2013-07-10.',
"Which titles are attached to the posts linked to from posts titled 'PCA or method of principal component for FA?'? Use the first 120 body characters for untitled posts.",
"Find the titles (or the first 120 body characters for untitled posts) for the posts linked to from posts titled 'Computing conditional expectations'.",
"Show the posts linked to from posts titled 'why l1 norm can result in variable selection but not l2' with titles (or the first 120 body characters for untitled posts), score and view counts.",
"What are the posts linked to from posts titled 'When does AIC lose its power to discriminate models?' called? Include a 120-character body excerpt instead of any missing title.",
'Give me the titles of the posts linked to from posts titled "Bonferroni correction with Pearson\'s correlation and linear regression", falling back to the first 120 characters of the body.',
'What did the comments written by the user with ID 25171 say? Show the first 120 characters of each comment.',
'Quote the beginning of each of the comments written by the user with ID 53222, limited to 120 characters.',
'What is the display name of the user with ID 35386?',
'Identify the user with ID 21559 by the saved display name.',
'Retrieve the display name for the user with ID 34735.',
'Show 120-character previews of the comments written by users who joined on 2012-04-26.',
'List the comments written by users who joined on 2014-08-18 with their scores and the first 120 characters of their text.',
'What text opens the comments written by users who joined on 2012-12-04? Return the first 120 characters of each comment.',
'Give brief excerpts from the comments written by users who joined on 2012-10-14: the first 120 text characters each.',
'Which question titles correspond to the questions to which answers created on 2014-06-03 respond? Use the first 120 body characters if untitled.',
'Find the question titles (or the first 120 body characters when untitled) of the questions to which answers created on 2013-09-30 respond.',
'For the questions to which answers created on 2014-04-24 respond, return the score beside each title, substituting the first 120 body characters for absent titles.',
'List the authors of posts linked to from posts created on 2014-07-11 with display names, reputation and locations.',
'Who wrote those posts? Show the display names of the authors of posts linked to from posts created on 2012-11-26.',
'I need to identify the authors of posts linked to from posts created on 2014-03-02; give their display names.',
'Show the titles of the questions created on 2014-03-04. An untitled question should be represented by its first 120 body characters.',
'Which names match the tags with stored usage count exactly 1?',
'List the names of the tags with stored usage count exactly 158.',
'What is the title of the question with ID 46804? If missing, give the first 120 characters of its body.',
'Find the title recorded for the question with ID 112864, using a 120-character body excerpt when untitled.',
"Who provided the accepted answers? Give display names for the authors of accepted answers to questions titled 'In SPSS, is there any way to define a use groups of data based on combinations of variables?'.",
"For the authors among the authors of accepted answers to questions titled 'Related sample t-test with missing values', show display names, reputation and locations.",
'Give me the opening 120 characters of the comments written by users with reputation exactly 751.',
"How many views have questions titled 'percentage of variance' received, according to their stored view counts?",
"What score is recorded for questions titled 'Identifiability in linear regression'?",
"Show the scores of questions titled 'How to Obtain “Right” Parameters of Multinomial Logit Model (or Other Conditional Models) in R?'.",
"When were questions titled 'Steps to write my own general equilibrium model in MATLAB' created? Return their creation dates and times.",
'What titles identify the posts commented on by the user with ID 38318? Represent untitled posts by their first 120 body characters.',
'Give the titles (or the first 120 body characters for untitled posts) associated with the posts commented on by the user with ID 17672.',
'List the titles for the posts commented on by the user with ID 48907; use the first 120 body characters wherever the title is absent.',
'Which post titles can be found among the posts authored by users who joined on 2014-06-29 who have badges? Substitute 120-character body excerpts for untitled posts.',
'Please show the titles (or the first 120 body characters for untitled posts) of the posts authored by users who joined on 2013-02-12 who have badges.',
'What posts did those users write? Give the titles (or the first 120 body characters for untitled posts) for the posts authored by users who joined on 2014-06-23.',
'For the posts authored by users who joined on 2014-07-18, retrieve titles with the first 120 body characters as the fallback.',
'Identify the posts authored by users who joined on 2014-07-31 by title; a missing title should be replaced with its first 120 body characters.',
'I am looking for the titles (or the first 120 body characters for untitled posts) belonging to the posts authored by users who joined on 2014-04-02.',
'Give titles or 120-character body excerpts for the posts authored by users who joined on 2014-05-29.',
"Which titles (or the first 120 body characters for untitled posts) represent the posts authored by the user 'Alan Melling' who have badges?",
"Return the titles of the posts authored by the user 'user2320' who have badges, using the first 120 body characters for untitled posts.",
'What posts are referenced? Show the titles (or the first 120 body characters for untitled posts) for the posts linked to from the post with ID 27215.',
'Which question is answered? Return the question titles (or the first 120 body characters when untitled) of the questions to which the answer with ID 32091 responds.',
'Show the title of the questions to which the answer with ID 70980 responds; if it is absent, return the first 120 body characters.',
'Identify the question among the questions to which the answer with ID 108082 responds by its title or its first 120 body characters.',
'Retrieve question titles (or the first 120 body characters when untitled), score and view counts for the questions to which the answer with ID 5311 responds.',
'I want the title of the questions to which the answer with ID 111660 responds, with a 120-character body excerpt if it is untitled.',
"For the comments written by the user 'Georgia', give scores and creation dates alongside the first 120 characters of each comment.",
"What are the first 120 characters of the comments written by the user 'Michael Holman'?",
"Let me read the beginnings of the comments written by the user 'BI Guy'; show the first 120 characters apiece.",
"List the opening text of the comments written by the user 'ziyuang', limited to 120 characters per comment.",
"Give the creation date and time of posts titled 'One-Way ANOVA experiment ideas'.",
'Give the titles (or the first 120 body characters for untitled posts) for posts by this user: the posts authored by the user with ID 12707.',
'What are the posts among the posts authored by the user with ID 37514 titled? Use the first 120 body characters as a fallback.',
"Show a title list for the posts authored by the user with ID 34828, substituting each untitled post's first 120 body characters.",
"Find the titles of the posts with revision activity by the user 'Wikis'; for an untitled post, show the first 120 characters of its body.",
'What tag names appear in the tags on posts authored by users who joined on 2012-02-21?',
'Which posts were revised? Return the titles (or the first 120 body characters for untitled posts) for the posts with revision activity by users who joined on 2012-10-26.',
'What are the titles (or the first 120 body characters for untitled posts) of the posts among the posts voted on by the user with ID 82?',
'I need titles for the posts voted on by the user with ID 4268, using the first 120 body characters when no title is available.',
'Give a unique list of titles (or the first 120 body characters for untitled posts) for the posts linked to from the post with ID 26141.',
"What distinct view counts are recorded for questions titled 'How to Obtain “Right” Parameters of Multinomial Logit Model (or Other Conditional Models) in R?'?",
"For questions titled 'Non-converging heteroscedastic linear mixed-effects model (R lme)', list the different scores.",
'Show the first 120 characters of the comments written by users with reputation exactly 29, with each distinct preview listed once.',
]
append_batch(0,q)
