"""Individually written questions, frozen after rendered-text review."""
from .v4_question_authoring import append_batch

q=[
"Which of the comments written by the user 'majom' has the highest score? Show the first 120 characters of its comment text.",
"Find the best-scoring comment among the comments written by the user 'Michael Holman' and return a preview of its first 120 characters.",
'What is the highest-scoring post among the posts authored by the user with ID 32236? Give its title or first 120 body characters if untitled.',
'Identify the post with the largest score in the posts authored by the user with ID 41224 by its title, using a 120-character body excerpt if absent.',
"Which of the wiki posts for the tag 'interaction' has the lowest score? Return its title or first 120 body characters.",
"Find the post that scores highest among the posts with revision activity by the user 'user3671'; show its title or, if untitled, its first 120 body characters.",
"Of all the posts commented on by the user 'MegPophealth', what percentage score above zero? Include unscored posts in the total.",
'What percentage of the accepted answers to questions created on 2011-04-06 have positive scores, counting answers with no score in the denominator?',
'How often are scores positive among the posts authored by users with reputation between 61 and 131 inclusive? Express the result as a percentage of all matching posts, including unscored ones.',
'What share of the questions to which the answer with ID 21671 responds has a score greater than zero? Give a percentage, using all matching questions as the total even if unscored.',
'Calculate the percentage of the posts linked to from posts created on 2012-12-19 whose score is positive; include posts without a score in the total.',
"Among the posts voted on by the user 'erikvold', what percentage have scores above zero? Count every matching post in the denominator.",
'How many percent of the posts linked to from posts with score between 7 and 11 inclusive have positive scores? Base the percentage on all those posts, including any with missing scores.',
'Give the positive-score percentage for the posts linked to from posts with score between 18 and 52 inclusive. Use the full set of matching posts, including unscored posts, as the denominator.',
'What percentage of all the accepted answers to questions with score between 1 and 5 inclusive have a positive score, with unscored answers still included in the total?',
'Considering the accepted answers to questions with score between 0 and 8 inclusive, how large is the share scoring above zero? Return a percentage of all matching answers, including unscored answers.',
'For the post with ID 38647, report the percentage of matching posts with a positive score. Include any missing score in the total.',
'What percentage of the questions among the questions to which answers with score exactly 4 respond score greater than zero? Keep unscored questions in the denominator.',
"For the posts titled 'Take the residual of a logistic regression model and use it as a response variable in another model', give the percentage of matching posts whose scores exceed zero, using all matching posts as the denominator.",
'Out of all the posts with score between 3 and 26 inclusive, what percentage have positive scores? Include unscored posts when calculating the total.',
"Calculate the positive-score share of the questions titled 'The distribution of STD/MAD for a Student' as a percentage of every matching question, including any without scores.",
"What proportion of the questions titled 'Overfitting times series data' score above zero? Answer as a percentage, counting all matching questions in the denominator.",
'How common are positive scores in the posts with revision activity by users with reputation between 11 and 42 inclusive? Give the percentage of all matching posts, including unscored ones.',
'What percentage of the posts with revision activity by users with reputation between 1 and 105 inclusive score positively? Divide by the full matching-post total, not just posts with scores.',
'Give the percentage scoring above zero among the posts with revision activity by users with reputation between 855 and 3518 inclusive, using every matching post as the denominator.',
'Among all the posts authored by the user with ID 44680, calculate the percentage with positive scores; missing scores remain in the total.',
"What share of the posts with revision activity by the user 'Reeza' score positively? Express it as a percentage of all matching posts, including those without scores.",
'For the posts commented on by the user with ID 10479, what is the percentage of posts with scores greater than zero? Include all matching posts in the denominator.',
'Find the positive-score percentage among the posts commented on by users who joined on 2010-12-30, keeping posts with missing scores in the total.',
'Of the questions with score between 1 and 10 inclusive, what percentage have scores above zero? Use every matching question, including any without a score, as the total.',
'Which of the questions to which answers created on 2012-10-02 respond has the highest score? Show the score and its title or first 120 body characters if untitled.',
"Give the title and score of the best-scoring post in the posts linked to from posts titled 'Use of R for biostatistics publications', replacing an absent title with its first 120 body characters.",
"Who has the greatest reputation among the authors of posts reached by following two successive post links from posts titled 'Minimum sample size for unpaired t-test'? Return the display name and reputation.",
"Identify the most reputable user in the authors of posts reached by following two successive post links from posts titled 'A one-way between subjects ANOVA', including the reputation alongside the display name.",
'For the posts commented on by users who joined on 2013-03-01, find the post with the largest score and show that score with its title or first 120 body characters.',
'Which tag among the tags with stored usage count between 4 and 624 inclusive has the highest stored usage count? Give its name and count.',
'Show the name and stored usage count of the most-used tag in the tags with stored usage count between 24 and 487 inclusive.',
"Which of the comments by authors of posts linked to from posts by the user 'hucsy' scores best? Return its score and the first 120 text characters.",
"Find the highest-scoring comment in the comments by authors of posts linked to from posts by the user 'Tomas'; include its score with a preview of its first 120 characters.",
"Give the score and first 120 body characters of the highest-scoring answer among the accepted answers to questions titled 'F-values in ANOVA table'.",
"What comment scores highest among the comments written by the user 'workglide'? Show its score and its opening 120 characters.",
'Which post in the posts authored by the user with ID 22474 has the best score? Give the title or first 120 body characters along with that score.',
"Find the top-scoring post among the posts with revision activity by the user 'user3441959' and return its score beside its title, using the first 120 body characters if untitled.",
"What is the average stored usage count of the different tags on posts commented on by the user 'Collin1'?",
'What score do the posts with score between 2 and 26 inclusive average?',
"Which of the posts authored by holders of the 'Mortarboard' badge has the lowest score? Show its score and title, substituting its first 120 body characters when untitled.",
"Find the worst-scoring post in the posts authored by holders of the 'Good Question' badge and provide its title or first 120 body characters together with its score.",
"What is the lowest-scoring answer among the accepted answers to questions titled 'Should one remove highly correlated variables before doing PCA?'? Give its score and first 120 body characters.",
"For the questions to which answers created on 2013-10-23 respond, return the lowest-scoring question's score and title, or its first 120 body characters if untitled.",
'Identify the post with the smallest score in the posts commented on by the user with ID 37196. Show the score and title or a 120-character body excerpt.',
"Which of the posts voted on by the user 'Eelvex' scores least? Include its score and its title, falling back to the first 120 body characters.",
"For users with badges in common with each named user, how much does the total reputation for 'Kroods' exceed that for 'user1331'? Subtract the second total from the first, counting each user once per named user.",
"Compare 'x3ja' with 'Donald Edwards' on combined reputation of users with badges in common with each named user. Return the first total minus the second; count each user once for each named user.",
"What is the difference in total reputation of authors of posts linked to from posts with revision activity by each named user for 'gillesc' versus 'deanj'? Subtract the latter total and count each author once per named user.",
"For authors of posts linked to from posts by each named user, subtract the reputation total associated with 'user10739' from the total associated with 'Nipun Valoor', once per author per named user.",
"How do 'atomant' and 'Vinay Tiwari' compare on the combined reputation of authors of posts linked to from posts by each named user? Give the first minus the second, counting each author once per named user.",
"Calculate the total reputation of authors of posts linked to from posts by each named user separately for 'Relax_Im_A_Quant' and 'Nuno Calaim'; report their difference in that order, once per author per named user.",
"Using authors of posts linked to from posts by each named user, what is the reputation-total difference between 'user29772' and 'herohuyongtao'? Return the former minus the latter and count each author once for each named user.",
'How many the posts with score between 3 and 11 inclusive have a score of at least 0?',
"Count the posts among the posts linked to from posts titled 'What is the difference between linear regression and logistic regression?' whose scores are at least 87.0.",
"Of the posts linked to from posts titled 'Example of auto-regressive integrated moving average (ARIMA) model', how many score 14.0 or more?",
"What number of the posts linked to from posts titled 'How can you have a non-significant multiple regression model w/ significant predictors?' reach a score of 1.0 or higher?",
"How many posts in the posts linked to from posts titled 'Difference between fuzzy graphical network , Markov model and Bayesian network' meet or exceed a score of 18.0?",
"For the posts authored by the user 'gct', give the count of posts scoring at least 1.0.",
"How many of the posts in the posts authored by the user 'Alexander Smola' have scores no lower than 4.0?",
"Count the posts authored by the user 'RubenGeert' with scores greater than or equal to 0.0.",
"What is the number of posts among the posts authored by the user 'Orestis Tsinalis' scoring 0.0 or above?",
'How many the questions to which answers created on 2012-03-15 respond have scores of at least 1.0?',
'Among the questions to which answers created on 2011-03-23 respond, count the questions reaching a score of 7.0. Include higher scores too.',
'What question count do you get from the questions to which answers created on 2013-05-27 respond if the score must be at least 4.0?',
'How many questions in the questions to which answers created on 2012-01-25 respond score no less than 26.0?',
'How many the questions with score between 1 and 2 inclusive score at least 1?',
'Count the questions in the questions with score between 0 and 6 inclusive with scores of 8 or higher.',
'What is the number of the questions with score between 1 and 8 inclusive meeting a minimum score of 1?',
'Among the questions with score between 1 and 4 inclusive, how many questions reach or exceed 4 points?',
"How many comments in the comments written by the user 'dmckee' have a score at least 1.0?",
"Count the comments written by the user 'qlinck' scoring 0.0 or more.",
'How many the users with reputation between 276 and 417 inclusive have reputation of at least 1?',
'What number of users in the users with reputation between 1 and 276 inclusive reach 121 reputation or above?',
'Count the users among the users with reputation between 101 and 283 inclusive whose reputation is no lower than 6.',
'How many users qualify within the users with reputation between 6 and 615 inclusive if reputation must be at least 23?',
'Give the number of the users with reputation between 26 and 138 inclusive meeting or exceeding 16 reputation.',
'Add the scores of the accepted answers to questions created on 2014-04-28 that score at least 4.0. What total results?',
"What is the combined score of the comments written by the user 'cosmoguy' with scores of 0.0 or more?",
"List the posts voted on by the user 'Matt Parker' with their scores and titles, using the first 120 body characters for missing titles. Order by post ID.",
'How many different posts authored by the user with ID 28609 are there?',
'How many distinct comments were written by authors of posts linked to from posts by the user with ID 18285?',
'What is the number of different comments by authors of posts linked to from posts by the user with ID 18393?',
"Which of the posts commented on by authors of posts linked to from posts titled 'Identify seasonality in time series data' have at least 3 distinct qualifying comments from those authors? Show titles or first-120-character body excerpts and the comment counts, ordered by post ID.",
"Which of the authors of accepted answers to questions titled 'How do I report a 4x4 ANOVA interaction' have at least 1 accepted answer to those questions? List display names with distinct answer counts, ordered by user ID.",
"How many distinct posts with revision activity by the user 'user3441959' with at least one comment are there?",
"Count the different posts among the posts with revision activity by the user 'Jason Samuels' with at least one comment.",
"How many different posts commented on by holders of the 'Mortarboard' badge that are questions are there?",
"Count the distinct questions among the posts commented on by holders of the 'nonlinear-regression' badge that are questions.",
"What is the highest score among the posts linked to from posts titled 'How princomp() works?'?",
"How large is the greatest reputation among the authors of posts linked to from posts with revision activity by the user 'celenius'?",
"What is the maximum reputation recorded for the authors of posts linked to from posts with revision activity by the user 'CCL'?",
"Find the largest score for the posts with revision activity by the user 'Susi_28'.",
"What is the smallest score among the posts voted on by the user 'Lorin Hochstein'?",
'Give the lowest reputation found among the authors of posts linked to from posts with revision activity by users who joined on 2014-01-05.',
]
append_batch(200,q)
