"""Individually written questions, frozen after rendered-text review."""
from .v4_question_authoring import append_batch

q=[
'Which different comment previews occur in the comments written by users with reputation exactly 14? Use the first 120 characters and suppress duplicate previews.',
'What unique titles (or the first 120 body characters for untitled posts) can you retrieve for the posts authored by the user with ID 6593 who have badges?',
'List the distinct question titles of the questions created on 2012-12-31, replacing absent titles with the first 120 body characters.',
'Give question titles (or the first 120 body characters when untitled) for the questions created on 2013-06-25, listing each different text once.',
'Which distinct tag names are found among the tags on posts authored by users who joined on 2013-07-25?',
'Find titles (or the first 120 body characters for untitled posts) for the posts authored by users with reputation exactly 83 and remove duplicate text from the answer.',
'Show each different title of the posts authored by users with reputation exactly 139 once; use the first 120 body characters when untitled.',
'I need the unique titles (or the first 120 body characters for untitled posts) of the posts authored by users with reputation exactly 63.',
"What different titles do the posts voted on by the user 'Queops' have? For untitled posts, use their first 120 body characters.",
'Give distinct previews of the accepted answers to questions titled \'What does "principled" mean, as in "principled Bayesian analysis"?\', taking the first 120 body characters of each answer.',
'Look up the post with ID 56722 and show its distinct title or 120-character body excerpt.',
'What unique title or first 120 body characters represent the post with ID 41004?',
'For the posts created on 2013-03-18, give each different title or 120-character body excerpt only once.',
"Which unique titles (or the first 120 body characters for untitled posts) identify the posts linked to from posts titled 'why l1 norm can result in variable selection but not l2'?",
"Collect the different titles of the posts linked to from posts titled 'PCA or method of principal component for FA?', with the first 120 body characters used for missing titles.",
"Return titles (or the first 120 body characters for untitled posts) for the posts linked to from posts titled 'Which test can I use to compare two sets of categorical data?' without repeated text.",
"I want a deduplicated title list for the posts linked to from posts titled 'When does AIC lose its power to discriminate models?'; use the first 120 body characters for untitled posts.",
'Which titles are distinct among the posts with revision activity by users who joined on 2013-07-15? Substitute first-120-character body excerpts where needed.',
'Show the different titles (or the first 120 body characters for untitled posts) belonging to the posts with revision activity by users who joined on 2014-01-16.',
'List each distinct title from the posts authored by users who joined on 2014-07-31, falling back to the first 120 body characters if absent.',
'What are the unique tag names for the tags on posts authored by the user with ID 11233?',
"For the tag 'hotelling', return its distinct stored usage count.",
"Which distinct scores belong to posts titled 'Trying to compare a fully fixed and and fully random model in R'?",
'For the posts commented on by the user with ID 10306, show a list of distinct titles or, when untitled, first-120-character body excerpts.',
'How many the accepted answers to questions with score between 0 and 7 inclusive are there?',
'What is the number of the accepted answers to questions with score between 1 and 28 inclusive?',
'How many users are included in the users who joined on 2013-12-18?',
'Count the posts created on 2012-05-10.',
'What total number of posts matches the posts created on 2014-02-24?',
'How many answers qualify as the accepted answers to questions created on 2013-11-19?',
'Give the number of posts among the posts linked to from posts created on 2010-10-19.',
'How large is the collection of the posts linked to from posts created on 2014-05-13?',
'How many comments belong to the comments written by users who joined on 2012-04-26?',
'Count the questions in the questions created on 2013-08-11.',
'What is the question count for the questions created on 2014-04-01?',
'How many questions were created as described by the questions created on 2013-08-04?',
'How many posts did this user write: the posts authored by the user with ID 29567?',
'Tell me the number of the posts authored by the user with ID 48375.',
'What post count do you get for the posts authored by the user with ID 37514?',
'Count the posts written by those users: the posts authored by users who joined on 2014-06-25.',
'How many comments did the user write among the comments written by the user with ID 10464?',
'What is the comment total for the comments written by the user with ID 40879?',
'How many authored posts are represented by the posts authored by users with reputation between 63 and 255 inclusive?',
'Give a count of the posts authored by users with reputation between 21 and 109 inclusive.',
'How many posts fall into the posts authored by users with reputation between 43 and 211 inclusive?',
"For the posts authored by the user 'Misscats', what is the total number of posts?",
"Count the posts attributed to this user: the posts authored by the user 'user6422'.",
'How many comments are in the comments written by users with reputation between 154 and 304 inclusive?',
"What number of comments did this user write, as described by the comments written by the user 'BI Guy'?",
"Give the comment count corresponding to the comments written by the user 'wrongusername'.",
'How many posts with a recorded title did the user with ID 35233 author? Return only the per-user counts.',
'Count the posts with a recorded title authored by the user with ID 29075; give only the per-user counts.',
'For the user with ID 16485, provide display names, post counts and reputation for their authored posts with a recorded title.',
'What is the number of authored posts with a recorded title for the user with ID 49012? Show only the per-user counts.',
'Among users who joined on 2014-05-29 who have written posts, how many posts did each write? Give only the per-user counts.',
'Which users who joined on 2014-05-22 have authored posts, and how many apiece? Show display names and post counts.',
'List display names and post counts for the authors among users who joined on 2014-08-05 who wrote at least one post.',
'For users who joined on 2014-07-18 and authored at least one untitled post, count their posts with no recorded title. Return only the per-user counts.',
'How many posts with no recorded title did each qualifying author among users who joined on 2013-04-08 write? Exclude users with none and show only the per-user counts.',
'Among users who joined on 2012-02-07 with untitled posts, give display names and post counts for the posts with no recorded title they authored.',
'What count of posts with no recorded title belongs to the user with ID 9007? Give only the per-user counts.',
'Show display names, post counts and reputation for the user with ID 14456, counting only their authored posts with no recorded title.',
'How many untitled posts were authored by the user with ID 25799? I need only the per-user counts.',
'Look up the user with ID 1287 and provide display names, post counts and reputation for their posts with no recorded title.',
"Give display names and post counts for the posts written by the user 'user25971'.",
"What number of posts has the user 'KevinL' authored? Return only the per-user counts.",
"For the user 'Leotardo', show display names and post counts based on all their authored posts.",
'Count posts with a recorded title per author among users who joined on 2013-07-05, excluding users with no such posts. Show only the per-user counts.',
'For users who joined on 2013-10-07 and wrote titled posts, provide display names, reputation and the number of authored posts with a recorded title.',
'How many titled posts did each author among users who joined on 2012-02-07 write? Include only authors with such posts and return only the per-user counts.',
"For the user 'user52335', how many authored posts have a recorded title? Give only the per-user counts.",
"What is the count of titled posts by the user 'blerg'? Return only the per-user counts.",
"Count the authored posts with a recorded title for the user 'Linda DeRegnaucourt', showing only the per-user counts.",
"Show display names and post counts for the untitled posts written by the user 'Mickaël S'.",
"How many posts with no recorded title were authored by the user 'nellaivijay'? Return only the count.",
'How many posts were written by the user with ID 29894? Return only the per-user counts.',
'Give the authored-post total for the user with ID 14456, showing only the per-user counts.',
'Count all posts by the user with ID 22175. I only need the count.',
'What is the total number of posts authored by the user with ID 45743?',
'For the user with ID 12707, return the number of authored posts.',
'Which of the questions to which answers created on 2012-11-25 respond has the highest score? Return its title or first 120 body characters if untitled.',
'Find the best-scoring question among the questions to which answers created on 2012-06-25 respond and show its title, using the first 120 body characters if absent.',
"What is the title of the highest-scoring post among the posts linked to from posts titled 'What are the important conditions in ANOVA fixed effects?'? Use a 120-character body excerpt if untitled.",
"Pick the post with the greatest score from the posts linked to from posts titled 'ANCOVA and its disturbing assumptions'; give its title or first 120 body characters.",
"Who has the highest reputation among the authors of posts reached by following two successive post links from posts titled 'Comparing categorized data'? Show the display name.",
"Name the most reputable user in the authors of posts reached by following two successive post links from posts titled 'Boxplot equivalent for heavy-tailed distributions?'.",
"Find the top user by reputation among the authors of posts reached by following two successive post links from posts titled 'masters program in statistics at a top 1 regional university vs a 3rd tier national university' and return the display name.",
'Which of the posts commented on by users who joined on 2014-06-24 scores highest? Identify it by title, or its first 120 body characters if untitled.',
'Give the title of the post with the largest score in the posts commented on by users who joined on 2011-12-16, substituting the first 120 body characters if necessary.',
'Among the posts commented on by users who joined on 2013-01-30, find the highest-scoring post and show its title or 120-character body excerpt.',
"Which of the accepted answers to questions titled 'How to interpret a differenced series with non zero mean?' has the lowest score? Show the first 120 characters of its body.",
'Find the lowest-scoring question among the questions to which answers created on 2014-05-28 respond; return its title or first 120 body characters.',
'Which question in the questions to which answers created on 2014-09-08 respond scores least? Give its title, with a 120-character body excerpt for a missing title.',
'Give the title of the worst-scoring question among the questions to which answers created on 2011-10-22 respond, using its first 120 body characters when untitled.',
'Which tag in the tags with stored usage count between 420 and 504 inclusive has the largest stored usage count? Give its name.',
'Name the most-used tag among the tags with stored usage count between 5 and 457 inclusive, based on the stored tag usage count.',
'Find the tag with the highest stored usage count in the tags with stored usage count between 277 and 292 inclusive and return the tag name.',
'Which of the posts commented on by the user with ID 49222 has the smallest score? Give its title or, when untitled, its first 120 body characters.',
"What answer scores highest among the accepted answers to questions titled 'PCA before random forest classification'? Return its first 120 body characters.",
"Identify the highest-scoring answer in the accepted answers to questions titled 'auto.arima does not recognize seasonal pattern' by its first 120 body characters.",
]
append_batch(100,q)
